const range=(key,label,min,max,step,value,unit='')=>({key,label,min,max,step,value,unit});
const select=(key,label,options,value)=>({key,label,options,value});
const quiz=(question,options,answer,tip)=>({question,options,answer,tip});
const task=(title,values,prompt)=>({title,values,prompt});
export const batch2 = [
 {
 id:'optics',noPrediction:true,title:'光學與透鏡成像實驗室',subject:'理化',grade:'國中',unit:'光學',minutes:'15–20',prior:'直線傳播、焦點、比例',
 description:'調整凸凹透鏡與物距，從兩條光線和像距讀值判斷實像、虛像與焦點奇異情況。',
 goals:['辨認實像與虛像的不同','比較物距、像距與放大率','說明物體在焦點時為何無法在有限距離成像'],
 controls:[select('kind','透鏡種類',[['convex','凸透鏡'],['concave','凹透鏡']],'convex'),range('f','焦距大小',5,30,1,10,'cm'),range('u','物距',2,100,1,30,'cm')],
 prediction:'依目前條件，會形成哪一類像？',choices:[['real','倒立實像'],['virtual','正立虛像'],['focus','沒有有限像距']],
 tasks:[task('① 物體在兩倍焦距外',{kind:'convex',f:10,u:30},'固定焦距10cm，比較物距30和40cm。像的位置與大小怎麼變？'),task('② 物體移到焦點內',{kind:'convex',f:10,u:5},'直接觀察像的方向與是否能投影，再和物距10cm比較。'),task('③ 換成凹透鏡',{kind:'concave',f:10,u:30},'保持物距，換成凹透鏡，觀察光線或反向延長線在哪裡相交。')],
 guide:[{say:'先看預設：焦距 10 cm 的凸透鏡，蠟燭放在 30 cm 處（在 2F 以外）。',check:{q:'成的像是？',from:'kind',options:[['real','倒立實像'],['virtual','正立虛像'],['focus','不成像']]},hint:'看讀值「像的性質」。',explain:'物體在 2F 以外，成倒立、縮小的實像。'},
  {say:'把蠟燭移近：物距改成 20 cm，剛好在 2F。',values:{},focus:'u',target:20,check:{q:'像距是多少？',from:'v',options:[['20','20 cm'],['15','15 cm'],['30','30 cm']]},hint:'看讀值「像距」。',explain:'物體在 2F，像也在另一側的 2F，而且和物體一樣大。'},
  {say:'再移近到焦點上：物距 10 cm。',values:{},focus:'u',target:10,check:{q:'這時會成像嗎？',from:'kind',options:[['real','成實像'],['virtual','成虛像'],['focus','不成像']]},hint:'看折射後的光線是否相交。',explain:'物體在焦點上，折射後的光線平行，不會相交成像。'},
  {say:'最後放進焦點以內：物距 5 cm。',values:{},focus:'u',target:5,check:{q:'成的像是？',from:'kind',options:[['real','倒立實像'],['virtual','正立虛像'],['focus','不成像']]},hint:'看虛線：反向延長線交會的地方。',explain:'物體在焦點以內，成正立、放大的虛像，這就是放大鏡的原理。'}],
 formula:'1/f = 1/u + 1/v；m = −v/u。凸透鏡 f>0，凹透鏡 f<0；實物 u>0。',
 limits:'理想薄透鏡、近軸光線；不計色差、球差及鏡片厚度。光線圖會等比例縮放以納入像的位置；焦點附近的極遠像可能讓物體顯得很小。虛線為反向延長線，不是真正反向行進的光。',
 misconception:'看得到虛像，不代表光線真的在虛像位置會合；實像是否清楚投在屏幕上，還要把屏幕放在像的位置。',
 safety:'不要用透鏡看太陽或聚焦陽光，本頁只提供安全模擬。',
 source:['OpenStax：透鏡成像','https://openstax.org/books/college-physics-2e/pages/25-6-image-formation-by-lenses'],related:[['../lenses.html','透鏡基礎教室'],['../convex-lens-imaging.html','凸透鏡成像演示']],
 quiz:[quiz('凸透鏡的物體位於焦點內時，形成？',['倒立實像','正立虛像','必定沒有像'],1,'將物距設為焦距的一半，觀察虛線交點。'),quiz('物體恰在凸透鏡焦點上，出射近軸光線？',['平行，無有限像距','在兩倍焦距相交','全部反射'],0,'平行光線不在有限距離交會。'),quiz('凹透鏡對實物形成的像通常？',['倒立放大','正立縮小','倒立等大'],1,'比較凹透鏡下的 v 正負與 |m|。')]
 },
 {
 id:'wave-sound',noPrediction:true,title:'波動、聲音與共振實驗室',subject:'理化',grade:'國中',unit:'波與聲',minutes:'15–20',prior:'頻率、週期與長度',
 description:'從波速、頻率與波長出發，比較開管與閉管的共振條件；不把音高和音量混為一談。',
 goals:['使用 v=fλ 解釋波長','比較開管與閉管的共振頻率','辨識位移的波節與波腹'],
 controls:[select('mode','觀察模型',[['travel','行進聲波'],['open','兩端開管'],['closed','一端閉管']],'travel'),range('f','驅動頻率',20,1000,1,340,'Hz'),range('v','聲速',300,360,1,340,'m/s'),range('length','管長／顯示長度',0.2,2,0.05,1,'m')],
 prediction:'目前條件的模型狀態是？',choices:[['travel','行進波比較'],['resonant','接近共振'],['off','偏離共振']],
 tasks:[task('① 頻率與波長',{mode:'travel',f:340,v:340,length:1},'只把頻率加倍，比較波長；注意聲速維持不變。'),task('② 開管基頻',{mode:'open',f:170,v:340,length:1},'固定長度1m，先觀察170Hz的狀態，再比較250Hz。'),task('③ 閉管與開管',{mode:'closed',f:85,v:340,length:1},'比較85、170、255Hz，不要假設所有整數倍都能共振。')],
 guide:[{say:'先看預設：頻率 340 Hz、聲速 340 m/s 的行進聲波。',check:{q:'波長是多少？',from:'wavelength',options:[['1','1 m'],['2','2 m'],['0.5','0.5 m']]},hint:'波長＝聲速÷頻率。',explain:'340÷340＝1 m。'},
  {say:'只把頻率加倍：改成 680 Hz。',values:{},focus:'f',target:680,check:{q:'波長變成？',from:'wavelength',options:[['1','1 m'],['2','2 m'],['0.5','0.5 m']]},hint:'看讀值「波長」。',explain:'聲速不變時，頻率加倍，波長就變成一半。'},
  {say:'換成兩端開口的管子（管長 1 m）。',values:{},focus:'mode',target:'open',check:{q:'340 Hz 會讓這支管子共振嗎？',from:'kind',options:[['resonant','會共振'],['off','不會共振']]},hint:'看讀值「與模態差距」。',explain:'開管的共振頻率是 170 Hz 的整數倍，340 Hz 剛好是第 2 個，所以共振。'},
  {say:'同一支開管，把頻率改成 300 Hz。',values:{mode:'open'},focus:'f',target:300,check:{q:'現在會共振嗎？',from:'kind',options:[['resonant','會共振'],['off','不會共振']]},hint:'比較 300 Hz 和最近的模態頻率。',explain:'300 Hz 不是 170 Hz 的整數倍，離最近的模態太遠，不會共振。'}],
 formula:'λ=v/f。兩端開管 fₙ=nv/(2L)；一端閉管 fₙ=(2n−1)v/(4L)。',
 limits:'理想一維空氣柱，不計管徑、端點修正及損耗。差距不超過最近模態頻率3%時標記「接近共振」，3%是介面教學容差，不是真實共振峰寬。曲線是空氣質點的縱向位移以橫向曲線表示，不是粒子沿曲線跑。開口是位移波腹，閉口是位移波節；壓力分布相反。',
 misconception:'頻率關聯音高，振幅關聯音量；共振不表示聲速突然增加。',safety:'本頁不播放聲音，避免教室突然出現大音量。',
 source:['OpenStax：空氣柱共振','https://openstax.org/books/college-physics-2e/pages/17-5-sound-interference-and-resonance-standing-waves-in-air-columns'],related:[['../waves.html','波動基礎教室']],
 quiz:[quiz('同一介質中頻率加倍，波長？',['加倍','不變','減半'],2,'保持聲速，以 λ=v/f 比較。'),quiz('一端閉管相對基頻具有哪些理想共振頻率？',['只有偶數倍','奇數倍','所有頻率'],1,'基頻、3倍、5倍符合一端波節一端波腹。'),quiz('開管端點的位移與壓力？',['位移波腹、壓力波節','兩者都是波節','兩者都是波腹'],0,'位移曲線和壓力曲線不要混用。')]
 },
 {
 id:'electromagnetism',noPrediction:true,title:'電磁鐵、馬達與發電機實驗室',subject:'理化',grade:'國中',unit:'電與磁',minutes:'20–25',prior:'電流、磁場、能量',
 description:'比較電流產生磁場、線圈受到轉矩，以及轉動線圈產生感應電壓三種方向不同的關係。',
 goals:['比較匝數與電流對磁場的影響','判斷線圈角度與轉矩','用磁通量變化解釋發電'],
 controls:[select('mode','裝置',[['magnet','空心電磁鐵'],['motor','線圈轉矩'],['generator','交流發電機']],'magnet'),range('turns','線圈匝數',10,200,10,100,'匝'),range('current','電流（電磁鐵／轉矩）',-2,2,0.1,1,'A'),range('field','外加磁場（轉矩／發電）',-0.5,0.5,0.05,0.2,'T'),range('angle','法線相對向右基準軸角度（轉矩／發電）',0,360,5,90,'°'),range('rpm','轉速（發電）',0,600,10,60,'rpm')],
 prediction:'主要輸出（磁場／轉矩／感應電壓）的正負為何？',choices:[['positive','正方向'],['zero','零'],['negative','負方向']],
 tasks:[task('① 電流反向',{mode:'magnet',turns:100,current:1},'比較+1A與−1A；匝數不變時磁場方向與大小怎麼變？'),task('② 線圈轉矩',{mode:'motor',angle:0,current:1,field:0.2,turns:100},'保持磁場為正，比較法線相對向右基準軸角度0°、90°、180°。'),task('③ 停止轉動',{mode:'generator',angle:90,field:0.2,rpm:0,turns:100},'從靜止到60rpm；再把磁場反向，比較感應電壓。')],
 guide:[{say:'先看電磁鐵：100 匝線圈通 1 A 電流。',check:{q:'線圈內的磁場方向？',from:'kind',options:[['positive','正向'],['zero','沒有磁場'],['negative','反向']]},hint:'看讀值「方向」。',explain:'通電線圈內部產生磁場，這就是電磁鐵。'},
  {say:'只把電流反過來：改成 −1 A。',values:{},focus:'current',target:-1,check:{q:'磁場方向變成？',from:'kind',options:[['positive','正向'],['zero','沒有磁場'],['negative','反向']]},hint:'看 N、S 極有沒有對調。',explain:'電流方向反過來，磁場方向也反過來，N、S 極對調。'},
  {say:'把電流調到 0。',values:{},focus:'current',target:0,check:{q:'現在線圈內？',from:'kind',options:[['positive','正向磁場'],['zero','沒有磁場'],['negative','反向磁場']]},hint:'看讀值「線圈內磁場」。',explain:'沒有電流就沒有磁場，所以電磁鐵可以開關。'},
  {say:'換成馬達的線圈：把法線角度轉到 0°，和磁場同方向。',values:{mode:'motor'},focus:'angle',target:0,check:{q:'線圈受到的轉矩？',from:'kind',options:[['positive','正向轉矩'],['zero','轉矩為 0'],['negative','反向轉矩']]},hint:'看讀值「轉矩」。',explain:'線圈平面和磁場垂直時轉矩為 0，所以馬達需要換向器繼續轉。'}],
 formula:'空心長螺線管 B=μ₀NI/ℓ（ℓ=0.20m）；τ=NBIA sinθ；ε=NBAω sinθ，ω=2π rpm/60，A=0.01m²。',
 limits:'電磁鐵採長螺線管近似；不計漏磁、鐵芯、電阻、發熱與反電動勢。馬達頁顯示當下轉矩而非自行推算轉速；發電機的轉速由外力維持。θ由固定向右基準軸量起；外加磁場B為有號分量，B<0代表向左，B=0時沒有磁場方向。轉矩正向取本圖順時針。正負只是固定繞線及法線約定，不是所有實際馬達的絕對方向。各模式只使用標示適用的控制。',
 misconception:'磁通量大不一定感應電壓大：電壓取決於磁通量改變的快慢。',safety:'不得短接電池或連接家用電源；真實線圈可能發熱。',
 source:['OpenStax：發電機','https://openstax.org/books/college-physics-2e/pages/23-5-electric-generators'],related:[['../dc-motor.html','直流馬達與換向器'],['../circuit-lab.html','電路實驗室']],
 quiz:[quiz('空心線圈電流反向，磁場？',['消失','方向反向','大小必定加倍'],1,'比較+I和−I。'),quiz('線圈法線平行磁場時轉矩？',['最大','無限大','零'],2,'此時 θ=0，sinθ=0。'),quiz('磁場固定，線圈完全停止且無其他變化時？',['沒有感應電壓','仍持續最大電壓','電壓隨時間增加'],0,'發電需要磁通量隨時間改變。')]
 },
 {
 id:'pressure-fluid',noPrediction:true,title:'氣壓、水壓與流體實驗室',subject:'理化',grade:'國中',unit:'壓力與流體',minutes:'15–20',prior:'力、面積、體積、密度',
 description:'分開觀察水深與液壓、密閉氣體的壓縮，以及水平管中截面、流速和壓力的關係。',
 goals:['分辨表壓和絕對壓力','在定溫條件下比較氣體壓縮','知道伯努力定律的使用限制'],
 controls:[select('mode','實驗',[['water','靜水壓'],['gas','定溫密閉氣體'],['flow','水平管內理想流動']],'water'),range('depth','深度（靜水）',0,10,0.5,2,'m'),range('density','液體密度（水壓／流動）',800,1200,50,1000,'kg/m³'),range('volume','氣體體積（氣體）',0.25,2,0.05,1,'L'),range('ratio','出口／入口面積比（流動）',0.4,2,0.1,1,''),range('speed','入口流速（流動）',0,4,0.5,2,'m/s')],
 prediction:'相對參考壓力101.3kPa，觀察位置的絕對壓力？',choices:[['higher','較高'],['same','相同'],['lower','較低']],
 tasks:[task('① 零深度與水下',{mode:'water',depth:0,density:1000},'比較0m和2m。表壓為零，是否代表完全沒有壓力？'),task('② 氣體壓縮一半',{mode:'gas',volume:0.5},'本模型維持溫度和氣體量不變；比較0.5L和1L。'),task('③ 窄管與流速',{mode:'flow',ratio:0.5,speed:2,density:1000},'只改變截面比，觀察出口流速和壓力；不要用此模型解釋所有風流。')],
 guide:[{say:'先看靜水壓：水深 2 m。',check:{q:'比參考壓力多了多少？',from:'gauge',options:[['19600','19.6 kPa'],['9800','9.8 kPa'],['0','0 kPa']]},hint:'看讀值「相對參考壓力」。',explain:'液壓＝密度×g×深度＝1000×9.8×2＝19600 Pa。'},
  {say:'只把深度加倍：改成 4 m。',values:{},focus:'depth',target:4,check:{q:'多出的壓力變成？',from:'gauge',options:[['39200','39.2 kPa'],['19600','19.6 kPa'],['78400','78.4 kPa']]},hint:'看讀值「相對參考壓力」。',explain:'深度加倍，液壓也加倍。'},
  {say:'深度回到 2 m，換成比較重的液體：密度 1200 kg/m³。',values:{},focus:'density',target:1200,check:{q:'多出的壓力變成？',from:'gauge',options:[['23520','23.52 kPa'],['19600','19.6 kPa'],['16333','16.33 kPa']]},hint:'液壓和密度成正比。',explain:'1200×9.8×2＝23520 Pa，密度越大，同深度的液壓越大。'},
  {say:'換成氣體實驗：把氣體壓縮成 0.5 L。',values:{mode:'gas'},focus:'volume',target:0.5,check:{q:'氣體壓力變成？',from:'absolute',options:[['202600','202.6 kPa'],['101300','101.3 kPa'],['50650','50.65 kPa']]},hint:'看讀值；溫度與氣體量都沒變。',explain:'體積變成一半，壓力變成兩倍（波以耳定律）。'}],
 formula:'水壓 P=P₀+ρgh，g=9.8m/s²；定溫氣體 PV=P₀V₀，V₀=1L；水平流 A₁v₁=A₂v₂，P₂=P₁+ρ(v₁²−v₂²)/2。',
 limits:'氣體模型定溫、定量；流動模型為穩態、不可壓縮、無黏性、同高的同一流線，入口壓力固定101.3kPa；不計水泵與摩擦，不適用高速氣流或汽化。截面圖是截面積示意，不是精確管徑比例。',
 misconception:'「流速大、壓力小」需符合條件；不能拿不同高度或不同流線任意比較。',safety:'不要自行加壓密閉容器；實驗用壓力設備需教師指導。',
 source:['OpenStax：伯努力方程式','https://openstax.org/books/college-physics-2e/pages/12-2-bernoullis-equation'],related:[['../buoyancy-density-lab.html','浮力與密度']],
 quiz:[quiz('水面表壓0kPa代表？',['沒有大氣壓','與參考大氣壓相同','絕對壓力為零'],1,'表壓是扣除外界參考壓力後的差值。'),quiz('定溫定量氣體體積減半，絕對壓力？',['減半','不變','加倍'],2,'由 PV=常數判斷。'),quiz('本水平理想流動模型中出口面積減半，出口流速？',['加倍','減半','變零'],0,'體積流率 A×v 保持一致。')]
 },
 {
 id:'solubility',noPrediction:true,title:'溶解度與濃度實驗室',subject:'理化',grade:'國中',unit:'物質與溶液',minutes:'15–20',prior:'溶質、溶劑、質量百分率',
 description:'用明確標示的教學溶解度曲線，分辨已溶解質量、未溶固體與溶液濃度。',
 goals:['正確使用每100g水的溶解度','分辨飽和、未飽和與剩餘固體','計算質量百分濃度並比較冷卻析出'],
 controls:[select('solute','教學溶質模型',[['a','模型A：溫度敏感'],['b','模型B：變化較小']],'a'),range('temperature','溫度',0,80,5,20,'°C'),range('water','水的質量',50,200,10,100,'g'),range('soluteMass','加入溶質質量',0,150,5,50,'g')],
 prediction:'達到平衡後，是否有未溶固體？',choices:[['none','沒有，未飽和'],['edge','沒有，恰好飽和'],['solid','有剩餘固體']],
 tasks:[task('① 飽和與剩餘固體',{solute:'a',temperature:20,water:100,soluteMass:50},'先記錄剩餘固體，再只增加水量。'),task('② 加熱與冷卻',{solute:'a',temperature:60,water:100,soluteMass:50},'記錄60°C的已溶解量，再降到20°C。兩筆相差多少？'),task('③ 濃度不是加入量除以水量',{solute:'b',temperature:20,water:100,soluteMass:100},'比較加入溶質與真正溶解的質量，算濃度時分母是哪一個？')],
 guide:[{say:'先看預設：20°C 時，把 50 g 溶質 A 加進 100 g 水。',check:{q:'溶質會？',from:'kind',options:[['none','全部溶解'],['edge','恰好飽和'],['solid','有剩餘固體']]},hint:'看讀值「未溶固體」。',explain:'20°C 時 100 g 水最多只能溶 30 g，多出的 20 g 沉在杯底。'},
  {say:'只把溫度提高到 60°C。',values:{},focus:'temperature',target:60,check:{q:'現在會？',from:'kind',options:[['none','全部溶解'],['edge','恰好飽和'],['solid','有剩餘固體']]},hint:'比較「最多可溶解」和加入的質量。',explain:'60°C 時最多可溶 50 g，剛好全部溶完，是飽和溶液。'},
  {say:'溫度回到 20°C，改成加 200 g 水。',values:{},focus:'water',target:200,check:{q:'現在會？',from:'kind',options:[['none','全部溶解'],['edge','恰好飽和'],['solid','有剩餘固體']]},hint:'水變多，最多可溶解的量也變多。',explain:'200 g 水最多可溶 60 g，50 g 全部溶解，還沒飽和。'},
  {say:'回到 100 g 水，只加 30 g 溶質。',values:{},focus:'soluteMass',target:30,check:{q:'20°C、100 g 水最多可溶解多少？',from:'capacity',options:[['30','30 g'],['50','50 g'],['60','60 g']]},hint:'看讀值「最多可溶解」。',explain:'溶解度由溫度與水量決定，不會因為加多少溶質而改變。'}],
 formula:'模型A：S=20+0.5T；模型B：S=35+0.025T（g/100g水）。容量=S×水量/100；已溶解=min(加入量,容量)；濃度=已溶解/(水+已溶解)×100%。',
 limits:'A、B是虛構的線性教學溶質，絕非硝酸鉀或食鹽的實測曲線。假設立即達平衡、不蒸發、不形成過飽和；只適用所示0–80°C範圍。真實溶解度需查該物質的實測資料。',
 misconception:'未溶解的固體不計入溶液質量百分濃度的分子或分母；攪拌通常改變速率，不等於改變平衡溶解度。',safety:'不提供可飲用或可混合的化學配方；本頁只做虛擬操作。',
 source:['NIST：實測溶解度資料庫','https://srdata.nist.gov/solubility/'],related:[['../particle-reaction-lab.html','粒子與化學反應']],
 quiz:[quiz('溶解度40g/100g水，50g水最多溶解？',['80g','40g','20g'],2,'水量減半，容量也減半。'),quiz('20g溶質完全溶於80g水，質量百分濃度？',['25%','20%','80%'],1,'分母為溶液總質量100g。'),quiz('本頁模型A能直接當作硝酸鉀實測資料嗎？',['可以','不可以，這是教學模型','只要改標題就可以'],1,'模型限制明確寫出A、B皆為虛構線性曲線。')]
 }
 ,{
 id:'energy',noPrediction:true,title:'能量轉換與守恆實驗室',subject:'理化',grade:'國中',unit:'力學與能量',minutes:'15–20',prior:'高度、速度、功與焦耳',
 description:'沿斜坡改變位置，追蹤重力位能、動能與摩擦產生的內能，檢查總能量帳。',
 goals:['比較位能下降與動能上升','把摩擦轉出的內能納入守恆','區分機械能守恆與總能量守恆'],
 controls:[range('mass','質量',0.5,5,0.5,1,'kg'),range('height','起始垂直高度',0.5,5,0.5,2,'m'),range('progress','沿斜坡下降比例',0,100,5,50,'%'),range('loss','位能減少量轉成內能的比例',0,100,5,0,'%')],
 prediction:'目前動能相對起點是？',choices:[['positive','大於零'],['zero','仍為零']],
 tasks:[task('① 無摩擦下坡',{mass:1,height:2,progress:50,loss:0},'記錄中點和坡底，檢查位能加動能。'),task('② 能量是否消失？',{mass:1,height:2,progress:100,loss:30},'和無摩擦比較，少掉的動能去了哪裡？'),task('③ 增加質量',{mass:2,height:2,progress:100,loss:0},'高度與損耗比例固定，質量加倍時能量和速度各如何改變？')],
 guide:[{say:'先看預設：1 kg 的推車從 2 m 高處出發。',check:{q:'總能量是多少？',from:'total',options:[['19.6','19.6 J'],['9.8','9.8 J'],['39.2','39.2 J']]},hint:'總能量＝mgh。',explain:'1×9.8×2＝19.6 J。'},
  {say:'讓推車滑到底：下降比例 100%。',values:{},focus:'progress',target:100,check:{q:'滑到底時的動能？',from:'kinetic',options:[['19.6','19.6 J'],['9.8','9.8 J'],['0','0 J']]},hint:'看讀值「動能」。',explain:'沒有摩擦時，位能全部變成動能。'},
  {say:'一樣滑到底，但有一半的位能變成內能：比例 50%。',values:{progress:100},focus:'loss',target:50,check:{q:'動能剩多少？',from:'kinetic',options:[['19.6','19.6 J'],['9.8','9.8 J'],['0','0 J']]},hint:'看讀值「動能」與「轉成內能」。',explain:'9.8 J 變成內能，動能只剩 9.8 J；總能量仍是 19.6 J。'},
  {say:'回到預設，只把質量改成 2 kg。',values:{},focus:'mass',target:2,check:{q:'總能量變成？',from:'total',options:[['19.6','19.6 J'],['39.2','39.2 J'],['9.8','9.8 J']]},hint:'看讀值；位能和質量成正比。',explain:'質量加倍，位能加倍：2×9.8×2＝39.2 J。'}],
 formula:'E₀=mgH；位能=mgH(1−s)；內能=mgHsη；動能=mgHs(1−η)；v=√(2gh下降(1−η))。g=9.8m/s²。',
 limits:'物體由靜止出發。以固定比例η描述沿程損耗，不是摩擦係數μ，也不是完整接觸力模型。η=100%僅表示指定位置的準靜態能量極限，不能解讀為物體會自行滑到該位置；位置由使用者指定，沒有求運動時間。',
 misconception:'有摩擦時機械能可以減少，但把系統內能納入後，總能量仍相同。',safety:'只用模擬觀察；不要用高處重物示範。',
 source:['OpenStax：能量守恆','https://openstax.org/books/college-physics-2e/pages/7-6-conservation-of-energy'],related:[['../force-motion-lab.html','力與運動'],['../heat-phase-lab.html','熱與物態']],
 quiz:[quiz('摩擦使動能比理想值少，能量主要轉為？',['消失','內能','質量'],1,'把物體、斜面與熱一起看作系統。'),quiz('無摩擦、相同高度由靜止滑下，質量加倍，底部速度？',['相同','加倍','減半'],0,'mgh=mv²/2 中的 m 可約去。'),quiz('η=100%時，本頁的位置滑桿代表？',['證明物體自行滑下','指定位置的極限能量帳，不是運動解','永動機'],1,'本模型沒有積分時間或求接觸力。')]
 },
 {
 id:'moon-eclipse',noPrediction:true,title:'月相、日食與月食實驗室',subject:'地科',grade:'國中',unit:'天文',minutes:'15–20',prior:'日月地相對位置與光影',
 description:'分開調整月球相位角與交點方向，理解為何每月有朔望，卻不會每月都有日月食。',
 goals:['連結月相與日月地位置','區分月相和地球陰影','說明交點附近才可能發生日月食'],
 controls:[range('phase','月球相位角（0°朔／180°望）',0,360,5,90,'°'),range('node','升交點相對太陽方向',0,360,5,90,'°'),range('inclination','軌道傾角',0,10,0.5,5,'°')],
 prediction:'以本頁對齊門檻判斷，目前是哪一種情況？',choices:[['solar','日食候選位置'],['lunar','月食候選位置'],['none','不在食的對齊範圍']],
 tasks:[task('① 朔不一定日食',{phase:0,node:90,inclination:5},'保持朔，把交點方向從90°改成0°，比較軌道偏離。'),task('② 望與月食',{phase:180,node:0,inclination:5},'先觀察望的位置，再把相位角改為90°比較。'),task('③ 沒有傾角的假想世界',{phase:0,node:90,inclination:0},'比較傾角0°和5°。為什麼現實不會每個朔望都發生食？')],
 formula:'可見亮面比例 k=(1−cosα)/2；軌道黃緯 β=asin(sin i × sin(α−Ω))。',
 limits:'圓軌道教學幾何；相位角近似黃經差，並非精密星曆。以離朔／望≤5°且|β|≤1°標記「食候選」，門檻只作教學，不能用來推算日期、食分、全食環食或地面可見地區。軌道俯視圖刻意放大天體，垂直偏離以讀值呈現。',
 misconception:'月相是看見月球被太陽照亮部分的比例，不是地球影子遮住月球。',safety:'不可直視太陽；本頁不是觀測日食的安全指引，也不是預報。',
 source:['NASA：月食與月球軌道','https://svs.gsfc.nasa.gov/4158/'],related:[['../moon-phases/','月相盈虧基礎教室']],
 quiz:[quiz('滿月時為何不一定發生月食？',['月球沒有被照亮','月球軌道傾斜，可能離開地影','地球停止公轉'],1,'固定望，改變交點方向看黃緯。'),quiz('上弦月通常可見亮面比例約？',['0%','50%','100%'],1,'相位角90°時 k=1/2。'),quiz('「日食候選」可以當作精確預報嗎？',['可以','不可以，僅是簡化對齊模型','可以預報所有城市'],1,'模型沒有星曆與地面觀測位置。')]
 },
 {
 id:'seasons',noPrediction:true,title:'四季與太陽高度角實驗室',subject:'地科',grade:'國中',unit:'天文',minutes:'15–20',prior:'緯度、地軸、角度',
 description:'改變緯度、地軸傾角與季節位置，比較正午太陽高度、日長及極晝極夜。',
 goals:['用地軸傾斜解釋季節','比較不同緯度的正午太陽高度','辨識極晝極夜與邊界'],
 controls:[range('latitude','緯度（北正南負）',-90,90,1,24,'°'),range('season','軌道位置（0°北半球春分）',0,360,5,90,'°'),range('tilt','地軸傾角',0,30,0.5,23.5,'°')],
 prediction:'此地今日的理想日長？',choices:[['long','長於12小時'],['equal','約12小時或地平線邊界'],['short','短於12小時']],
 tasks:[task('① 臺中夏冬比較',{latitude:24,season:90,tilt:23.5},'記錄北半球夏至，再把位置改到270°，比較正午高度與日長。'),task('② 南北半球',{latitude:-24,season:90,tilt:23.5},'同一公轉位置，緯度正負交換；季節相同嗎？'),task('③ 極圈與地軸',{latitude:70,season:90,tilt:23.5},'觀察70°N的日長，再把傾角調到0°。')],
 formula:'δ=asin(sinε sinλ)；正午高度 h=90°−|φ−δ|；日長=24 arccos(−tanφ tanδ)/π。極點需另外判斷。',
 limits:'理想圓軌道；不計折射、太陽視半徑、地形和近日點速度差，因此日長不是實際日出日落預報。極點且δ=0時太陽中心整日貼地平線，介面以邊界狀態代替一般日長。',
 misconception:'地軸方向與傾斜造成日照差異；不能用地球離太陽近或遠解釋南北半球相反的季節。',safety:'不可直接凝視太陽量測角度。',
 source:['NASA：四季成因','https://spaceplace.nasa.gov/seasons/en/'],related:[['moon-eclipse.html','月相、日食與月食']],
 quiz:[quiz('北半球夏至時南半球通常？',['同樣夏季','冬季','沒有季節'],1,'南北緯度交換後比較日長。'),quiz('地軸不傾斜的理想模型，大部分緯度的日長？',['每天24小時','每天0小時','全年約12小時'],2,'δ=0；極點是地平線特殊邊界。'),quiz('極夜時正午太陽高度可能？',['小於0°','一定90°','一定45°'],0,'太陽中心在地平線下。')]
 },
 {
 id:'plant-exchange',noPrediction:true,title:'呼吸作用、蒸散與氣孔實驗室',subject:'生物',grade:'國中',unit:'植物生理',minutes:'15–20',prior:'光合作用、呼吸作用、水分運輸',
 description:'用相對量比較植物白天與黑暗中的淨氣體交換，另看濕度和氣孔開度如何影響蒸散。',
 goals:['區分總光合作用與淨交換','說明植物在黑暗仍可呼吸','比較氣孔開度、濕度與水分散失'],
 controls:[range('light','相對光照',0,100,5,60,'%'),range('temperature','溫度',10,35,1,25,'°C'),range('humidity','相對濕度',0,100,5,50,'%'),range('stomata','氣孔開度（控制設定）',0,100,5,60,'%')],
 prediction:'此模型的淨氧氣交換方向？',choices:[['release','淨釋出氧氣'],['balanced','淨交換接近零'],['consume','淨消耗氧氣']],
 tasks:[task('① 白天和黑暗',{light:60,temperature:25,humidity:50,stomata:60},'保持氣孔與溫度，記錄有光與光照0%的淨氧氣交換。'),task('② 乾燥與潮濕',{light:60,temperature:25,humidity:20,stomata:60},'只改濕度20%→80%，比較蒸散指標，不把不同變因一起改。'),task('③ 氣孔關閉',{light:60,temperature:25,humidity:50,stomata:0},'觀察蒸散與氣體交換；模型中的呼吸是否仍存在？')],
 formula:'教學指標：總光合P=12[L/(L+30)]·s·exp(−((T−25)/15)²)；呼吸R=2·2^((T−25)/10)；淨氧=P−R；蒸散E=s(1−RH)·2^((T−25)/10)。s與RH為0–1比例。',
 limits:'所有速率是無單位的相對教學指標，非特定植物實測值；不推算生物產量。氣孔開度由學生固定，不模擬乾旱關孔回饋、風、葉面積與邊界層。溫度公式限10–35°C，不可外推。呼吸與蒸散是不同過程；氣孔全閉時仍保留呼吸代謝簡化項。',
 misconception:'植物不只在晚上呼吸；白天也同時呼吸，只是淨交換可能由光合作用主導。',safety:'不要把模型數值當作栽培處方，也不需密閉或加熱活體植物。',
 source:['OpenStax：水分運輸','https://openstax.org/books/biology-2e/pages/30-5-transport-of-water-and-solutes-in-plants'],related:[['../photosynthesis-factor-lab.html','光合作用限制因子']],
 quiz:[quiz('黑暗中植物通常仍會？',['只做光合作用','進行呼吸作用','不進行任何代謝'],1,'光照0%時總光合為0，呼吸項仍在。'),quiz('其他條件相同、氣孔開度固定，空氣濕度越高，蒸散指標？',['較低','較高','一定不變'],0,'比較水氣差異，而不是把蒸散和呼吸當成一件事。'),quiz('本頁的氣孔開度與蒸散值屬於？',['植物實測資料','所有植物通用常數','簡化教學設定與相對指標'],2,'真實植物還有水分壓力與氣孔回饋。')]
 },
 {
 id:'ecosystem',noPrediction:true,title:'生態系、食物網與族群實驗室',subject:'生物',grade:'國中',unit:'生態',minutes:'20–25',prior:'生產者、消費者、能量',
 description:'先讀懂食物網箭頭，再比較營養階層能量與單一族群的承載量模型。',
 goals:['辨認食物網箭頭代表能量由食物到取食者','比較階層能量傳遞','區分單族群邏輯斯成長與完整食物網動態'],
 controls:[range('energy','生產者可用能量',1000,10000,500,10000,'kJ／指定期間'),range('efficiency','每階層傳遞比例',5,25,1,10,'%'),range('initial','單一草食族群初始數量',10,300,10,50,'隻'),range('capacity','環境承載量K',50,500,25,200,'隻'),range('rate','內在成長率r',0,0.5,0.05,0.2,'／時間單位'),range('time','經過時間',0,30,1,10,'時間單位')],
 prediction:'此族群在指定時間的數量，相對初始值？',choices:[['grow','增加'],['steady','不變'],['decline','減少']],
 tasks:[task('① 能量不是循環',{energy:10000,efficiency:10},'記錄每階層能量，再把傳遞比例調到20%；不要改成100%定律。'),task('② 接近承載量',{initial:50,capacity:200,rate:0.2,time:10},'記錄時間10和30，觀察族群曲線是否一直同速增加。'),task('③ 超出承載量',{initial:300,capacity:100,rate:0.2,time:10},'觀察N₀>K的結果。這是否能推算整個食物網的真實變化？')],
 formula:'每階層能量Eₙ=E₀ηⁿ；N(t)=K/[1+(K/N₀−1)e^(−rt)]。r=0或t=0時N=N₀。',
 limits:'食物網為關係圖，不是與族群曲線耦合的多物種模型。能量圖是簡化鏈，不把同一能量重複分給各分支；傳遞效率由學生指定，10%不是定律。族群模型假設K、r固定，無遷移、年齡結構、季節、掠食與隨機災害；數值是連續期望量。',
 misconception:'物質可循環，能量沿食物網流動並逐步以熱散失；生物彼此連結不代表所有族群必定同時增加。',safety:'不以抓捕、釋放或傷害生物來驗證本模型。',
 source:['OpenStax：環境限制與族群成長','https://openstax.org/books/biology-2e/pages/45-3-environmental-limits-to-population-growth'],related:[['../photosynthesis-factor-lab.html','光合作用'],['plant-exchange.html','植物交換']],
 quiz:[quiz('食物網中草→兔表示？',['草吃兔','能量由草傳給兔','兔一定增加'],1,'箭頭從被吃者指向取食者。'),quiz('當N=K且環境不變，邏輯斯模型的成長率？',['零','無限大','一定為負'],0,'dN/dt=rN(1−N/K)。'),quiz('10%營養階層傳遞效率是？',['每個生態系的精確定律','可用的教學近似，實際會變','代表其餘90%不存在'],1,'其餘能量可能呼吸成熱、未被取食或進入碎屑途徑。')]
 },
 {
 id:'motion-graphs',noPrediction:true,title:'直線運動圖表實驗室',subject:'理化',grade:'國中',unit:'直線運動',minutes:'15–20',prior:'位置、位移、速度與加速度',
 description:'調整初速度與加速度，對照 x-t 圖與 v-t 圖：從斜率讀速度、從面積讀位移，並分辨位移與路徑長。',
 goals:['由 x-t 圖的斜率讀出速度','由 v-t 圖與時間軸圍成的面積讀出位移','分辨位移與路徑長，判斷物體何時折返'],
 controls:[range('v0','初速度',-10,10,1,10,'m/s'),range('a','加速度',-5,5,0.5,-5,'m/s²'),range('t','觀察時間',1,10,1,4,'s')],
 prediction:'這段時間內，物體的運動屬於哪一種？',choices:[['rest','靜止'],['uniform','等速度運動'],['speeding','速度大小越來越大'],['slowing','減速中，尚未折返'],['reversing','已減速到零並折返']],
 tasks:[task('① 等速度',{v0:5,a:0,t:4},'讀 x-t 圖的斜率和 v-t 圖的高度，兩個數字一樣嗎？'),task('② 只改加速度',{v0:0,a:2,t:4},'記錄加速度 2 m/s² 的位移，再只把加速度改成 4 m/s²，比較 v-t 圖下的面積。'),task('③ 位移是零',{v0:10,a:-5,t:4},'位移是 0，物體真的沒有動嗎？比較位移和路徑長。')],
 guide:[{say:'先看預設：初速 10 m/s、加速度 −5 m/s²，觀察 4 秒。',check:{q:'這段運動？',from:'kind',options:[['reversing','中途折返'],['slowing','一直減速'],['uniform','等速']]},hint:'看速度圖有沒有穿過時間軸。',explain:'速度從正變成負，表示中途折返。'},
  {say:'只把加速度改成 0。',values:{},focus:'a',target:0,check:{q:'運動變成？',from:'kind',options:[['reversing','中途折返'],['slowing','一直減速'],['uniform','等速']]},hint:'看速度圖是不是水平線。',explain:'加速度 0，速度不變；位置圖是一條斜直線。'},
  {say:'回到預設，只觀察 2 秒。',values:{},focus:'t',target:2,check:{q:'2 秒內的位移？',from:'x',options:[['10','10 m'],['20','20 m'],['0','0 m']]},hint:'位移＝速度圖下方的面積。',explain:'速度圖在時間軸上方的三角形面積：10×2÷2＝10 m。'},
  {say:'回到 4 秒，比較位移和路徑長。',values:{},check:{q:'4 秒的路徑長是多少？',from:'path',options:[['20','20 m'],['0','0 m'],['10','10 m']]},hint:'路徑長＝軸上與軸下的面積相加。',explain:'位移是 0（回到原點），但實際走了 10＋10＝20 m。'}],
 formula:'v＝v₀＋at；x＝v₀t＋½at²。v-t 圖的斜率＝加速度 a；v-t 圖與時間軸圍成的面積＝位移（時間軸上方為正、下方為負）；x-t 圖的切線斜率＝瞬時速度。',
 limits:'只討論直線上的等加速度運動，出發位置 x＝0，正方向由學生自訂。加速度在整段觀察時間內固定；真實物體的加速度可能隨時改變。本頁不處理受力的原因，受力請到「力與運動實驗室」。路徑長是折返前、後兩段位移大小的和。',
 misconception:'v-t 圖的線往下走，不代表物體往回走；要看速度的正負號，而不是看線的方向。',safety:'實際用軌道小車測量時，軌道末端要有擋板，避免小車衝出掉落。',
 source:['OpenStax：一維運動的圖形分析','https://openstax.org/books/college-physics-2e/pages/2-8-graphical-analysis-of-one-dimensional-motion'],related:[['../force-motion-lab.html','力與運動實驗室'],['energy.html','能量轉換與守恆']],
 quiz:[quiz('v-t 圖是一條往右下斜的直線，但整條線都在時間軸上方，物體？',['正在往回走','仍往正方向前進，但越來越慢','靜止不動'],1,'看速度的正負號，不是看線的方向。'),quiz('v-t 圖與時間軸圍成的面積代表？',['加速度','位移（軸下方算負）','一定等於路徑長'],1,'折返時，軸上方與下方的面積會互相抵消一部分。'),quiz('x-t 圖是一條水平線，物體？',['靜止','等速度運動','等加速度運動'],0,'x-t 圖的斜率就是速度，水平線的斜率是 0。')]
 },
 {
 id:'lever-torque',noPrediction:true,title:'槓桿與力矩實驗室',subject:'理化',grade:'國中',unit:'力與簡單機械',minutes:'15–20',prior:'力的大小與方向、支點',
 description:'在支點兩側掛重物與施力，比較兩側力矩；把施力改成斜著拉，找出真正的力臂是哪一段距離。',
 goals:['用「力矩＝力×力臂」判斷槓桿是否平衡','說明兩側力不一樣大卻能平衡的原因','找出力臂是支點到力的作用線的垂直距離'],
 controls:[range('w1','左側重物',1,20,1,10,'N'),range('d1','左側重物距支點',5,50,5,20,'cm'),range('f2','右側施力',1,20,1,5,'N'),range('d2','右側施力點距支點',5,50,5,40,'cm'),range('angle','施力與槓桿的夾角',30,150,10,90,'°')],
 prediction:'這組設定下，槓桿會？',choices:[['balanced','保持平衡'],['left','左側下沉'],['right','右側下沉']],
 tasks:[task('① 兩邊力不一樣大',{w1:10,d1:20,f2:5,d2:40,angle:90},'左邊 10 N、右邊只有 5 N，為什麼能平衡？比較兩側力矩。'),task('② 只改施力點',{w1:10,d1:20,f2:5,d2:20,angle:90},'施力點移到 20 cm，槓桿還平衡嗎？只改一個條件，要怎麼調才能再平衡？'),task('③ 斜著拉',{w1:10,d1:20,f2:5,d2:40,angle:30},'力的大小沒變，只把施力方向改成與槓桿夾 30°，為什麼不平衡了？看紅色虛線。')],
 guide:[{say:'先看預設：左邊 10 N 的重物掛在 20 cm，右邊用 5 N 在 40 cm 處往下拉。',check:{q:'槓桿現在的狀態是？',from:'kind',options:[['balanced','保持平衡'],['left','左側下沉'],['right','右側下沉']]},hint:'看讀值「槓桿狀態」，或比較左右兩側力矩。',explain:'左右兩側力矩都是 2 N·m，所以平衡。'},
  {say:'只改一個條件：把右側施力點移到 20 cm。',values:{},focus:'d2',target:20,check:{q:'哪一側下沉？',from:'kind',options:[['balanced','保持平衡'],['left','左側下沉'],['right','右側下沉']]},hint:'比較左右兩側力矩，力矩大的一側下沉。',explain:'右側力臂變短，右側力矩只剩 1 N·m，比左側小，所以左側下沉。'},
  {say:'要讓槓桿再平衡：施力點維持 20 cm，把右側施力加大到 10 N。',values:{d2:20},focus:'f2',target:10,check:{q:'現在槓桿？',from:'kind',options:[['balanced','保持平衡'],['left','左側下沉'],['right','右側下沉']]},hint:'看讀值「槓桿狀態」。',explain:'力臂剩一半，力就要加倍，兩側力矩又都是 2 N·m。'},
  {say:'回到預設，這次改變施力方向：把施力與槓桿的夾角改成 30°。',values:{},focus:'angle',target:30,check:{q:'右側的有效力臂是多少？',from:'effective',options:[['40','40 cm'],['20','20 cm'],['10','10 cm']]},hint:'看讀值「右側有效力臂」，也就是圖上紅色虛線的長度。',explain:'斜著拉時，力臂是支點到力的作用線的垂直距離：40×sin30°＝20 cm。'}],
 formula:'力矩＝力×力臂。左力矩＝w₁×d₁；右力矩＝F₂×d₂×sinθ，其中 d₂ sinθ 是支點到力的作用線的垂直距離（有效力臂）。兩側力矩相等時槓桿平衡。1 N·cm＝0.01 N·m。',
 limits:'理想輕槓桿：不計槓桿本身重量、支點摩擦與槓桿彎曲。重物鉛直向下；右側施力方向由夾角設定，都朝向讓右側下沉的一方。圖中槓桿傾斜固定畫 8°，只表示轉動方向，不是實際停下的角度。',
 misconception:'力臂不是「施力點到支點的距離」，而是「支點到力的作用線的垂直距離」；斜著施力時，有效力臂會變短。',safety:'真實槓桿實驗要注意重物掉落與手指被夾；掛重物前先確認掛勾牢固。',
 source:['OpenStax：力矩與平衡的第二條件','https://openstax.org/books/college-physics-2e/pages/9-2-the-second-condition-for-equilibrium'],related:[['motion-graphs.html','直線運動圖表'],['../force-motion-lab.html','力與運動實驗室']],
 quiz:[quiz('左邊 10 N 的重物掛在 20 cm 處，右邊在 40 cm 處垂直向下施力，多大才能平衡？',['5 N','10 N','20 N'],0,'兩側力矩相等：10×20＝F×40。'),quiz('施力大小與施力點不變，只把施力方向從垂直改成斜的，右側力矩會？',['變大','變小','不變'],1,'有效力臂＝d×sinθ，θ 不是 90° 時比 d 短。'),quiz('力臂指的是？',['施力點到支點的距離','支點到力的作用線的垂直距離','力的大小'],1,'看圖中從支點畫出的紅色虛線。')]
 },
 {
 id:'pulley-incline',noPrediction:true,title:'滑輪與斜面實驗室',subject:'理化',grade:'國中',unit:'簡單機械與功',minutes:'15–20',prior:'力、功＝力×距離',
 description:'用定滑輪、動滑輪、滑輪組與斜面把同一個重物舉高，比較施力、施力移動的距離和做的功：省力的機械會不會省功？',
 goals:['比較定滑輪、動滑輪、滑輪組與斜面的施力大小','發現省力時施力移動的距離會變長','用輸入功與輸出功說明「省力不省功」'],
 controls:[select('mode','裝置',[['fixed','定滑輪'],['movable','動滑輪'],['block','滑輪組'],['incline','斜面']],'fixed'),range('load','物重',10,200,10,100,'N'),range('n','承重繩段數（滑輪組）',2,6,1,4,'段'),range('h','上升高度',0.5,3,0.5,1,'m'),range('len','斜面長（斜面）',1,10,0.5,4,'m'),range('loss','摩擦損耗',0,50,5,0,'%')],
 prediction:'這組設定下，輸入功和輸出功的關係是？',choices:[['ideal','相等（沒有損耗）'],['lossy','輸入功比輸出功大（有損耗）']],
 tasks:[task('① 定滑輪省力嗎？',{mode:'fixed',load:100,h:1,loss:0},'讀施力和物重，再看施力移動的距離。定滑輪改變了什麼？'),task('② 換成動滑輪',{mode:'movable',load:100,h:1,loss:0},'施力變成一半，施力移動的距離呢？輸入功有沒有變？'),task('③ 加入 20% 損耗',{mode:'movable',load:100,h:1,loss:20},'和任務②比較：哪些數字變了、哪些沒變？')],
 guide:[{say:'先看定滑輪：把 100 N 的木箱拉高 1 m。',check:{q:'需要多少施力？',from:'force',options:[['100','100 N'],['50','50 N'],['25','25 N']]},hint:'看讀值「施力」。',explain:'定滑輪不省力，只改變施力方向。'},
  {say:'換成動滑輪。',values:{},focus:'mode',target:'movable',check:{q:'施力變成？',from:'force',options:[['100','100 N'],['50','50 N'],['25','25 N']]},hint:'看有幾段繩子一起撐住木箱。',explain:'兩段繩子分擔重量，施力變成一半；但繩子要拉 2 m。'},
  {say:'同樣用動滑輪，加入 20% 的摩擦損耗。',values:{mode:'movable'},focus:'loss',target:20,check:{q:'施力變成？',from:'force',options:[['50','50 N'],['62.5','62.5 N'],['40','40 N']]},hint:'有損耗時，實際施力＝理想施力÷效率。',explain:'50÷0.8＝62.5 N；多出來的功變成熱。'},
  {say:'換成斜面：長 4 m、高 1 m。',values:{},focus:'mode',target:'incline',check:{q:'沿斜面推需要多少力？',from:'force',options:[['25','25 N'],['100','100 N'],['50','50 N']]},hint:'看讀值「施力」。',explain:'100×1÷4＝25 N：推的距離是高度的 4 倍，力就是四分之一。'}],
 formula:'理想施力：定滑輪 F＝W、動滑輪 F＝W／2、滑輪組 F＝W／n、斜面 F＝W×h／L。施力移動距離：h、2h、n×h、L。輸出功＝W×h；效率 η＝1－損耗；實際施力＝理想施力／η；輸入功＝實際施力×移動距離。',
 limits:'滑輪與繩子沒有重量，繩子不會伸長；n 為承重繩段數。摩擦損耗以固定比例 η 表示，不是摩擦係數。斜面長不可短於上升高度，設定比高度短時以斜面長＝高度計算並提示。物體緩慢等速移動，不計動能。',
 misconception:'省力的機械不省功：施力變小，施力移動的距離就變長；理想情況下輸入功＝輸出功，有摩擦時輸入功更大。',safety:'真實操作滑輪時，重物下方不可站人，繩子不要纏在手上。',
 source:['OpenStax：簡單機械','https://openstax.org/books/physics/pages/9-3-simple-machines'],related:[['lever-torque.html','槓桿與力矩'],['energy.html','能量轉換與守恆']],
 quiz:[quiz('用理想動滑輪把 100 N 的重物舉高 1 m，施力與施力移動距離分別是？',['50 N、1 m','50 N、2 m','100 N、2 m'],1,'施力減半，繩子要拉兩倍長。'),quiz('理想情況下，使用滑輪組舉起重物時？',['省力也省功','省力但不省功','不省力也不省功'],1,'輸入功＝施力×移動距離＝輸出功。'),quiz('加入摩擦損耗後，哪一項不會改變？',['施力','輸入功','輸出功（W×h）'],2,'重物被舉高的高度與重量都沒變。')]
 },
 {
 id:'reaction-rate',noPrediction:true,title:'反應速率實驗室',subject:'理化',grade:'國中',unit:'反應速率',minutes:'15–20',prior:'粒子碰撞、濃度、溫度',
 description:'改變濃度、溫度、顆粒大小與催化劑，比較反應完成要多久；再確認最後生成的產物有沒有變多。',
 goals:['用控制變因比較濃度、溫度、顆粒大小與催化劑對反應快慢的影響','由產物—時間曲線的斜率讀出反應快慢','區分「反應多快」與「最後生成多少」'],
 controls:[range('conc','反應物濃度',0.1,2,0.1,1,'M'),range('temp','溫度',5,65,5,25,'°C'),select('size','固體顆粒',[['lump','塊狀（×1）'],['granule','顆粒（×3）'],['powder','粉末（×9）']],'lump'),select('cat','催化劑',[['none','無'],['yes','有（×4）']],'none'),range('amount','固體反應物的量',1,10,1,5,'單位')],
 prediction:'和基準條件（1 M、25°C、塊狀、無催化劑）相比，這次反應？',choices:[['slower','比基準慢'],['same','和基準一樣快'],['faster','比基準快']],
 tasks:[task('① 記錄基準',{conc:1,temp:25,size:'lump',cat:'none',amount:5},'先記下基準條件的完成時間與產物總量，之後每次只改一個條件。'),task('② 只升溫 10°C',{conc:1,temp:35,size:'lump',cat:'none',amount:5},'溫度從 25°C 改成 35°C，完成時間變成多少？'),task('③ 加入催化劑',{conc:1,temp:25,size:'lump',cat:'yes',amount:5},'反應變快了，最後的產物有比較多嗎？比較曲線的終點高度。')],
 guide:[{say:'先看基準：1 M、25°C、塊狀、沒有催化劑。',check:{q:'完成時間是多少？',from:'time',options:[['300','300 s'],['150','150 s'],['600','600 s']]},hint:'看讀值「完成時間」。',explain:'這是基準條件，之後每次只改一個條件和它比較。'},
  {say:'只把溫度提高 10°C：35°C。',values:{},focus:'temp',target:35,check:{q:'完成時間變成？',from:'time',options:[['300','300 s'],['150','150 s'],['600','600 s']]},hint:'本頁的經驗法則：每升高 10°C 速率加倍。',explain:'速率加倍，完成時間變成一半。'},
  {say:'溫度回到 25°C，加入催化劑。',values:{},focus:'cat',target:'yes',check:{q:'最後的產物總量？',from:'product',options:[['5','還是 5 單位'],['20','變成 20 單位']]},hint:'比較曲線的終點高度。',explain:'催化劑只讓反應變快，產物的量由反應物的量決定。'},
  {say:'拿掉催化劑，把塊狀改成粉末。',values:{},focus:'size',target:'powder',check:{q:'相對速率變成？',from:'rate',options:[['9','9 倍'],['3','3 倍'],['1','不變']]},hint:'看讀值「相對速率」。',explain:'顆粒越細，接觸面積越大，反應越快。'}],
 formula:'相對速率＝濃度×2^((溫度−25)/10)×顆粒係數×催化劑係數；完成時間＝固體反應物的量×60÷相對速率（秒）；產物總量＝固體反應物的量。基準條件的相對速率為 1。',
 limits:'本頁是教學用的虛構模型：「每升高 10°C 速率加倍」只是粗略經驗法則，真實反應各不相同；顆粒係數（×1、×3、×9）與催化劑倍數（×4）為虛構教學值。固體反應物全部用完即完成，濃度視為維持不變，反應速率在過程中固定，實際反應通常會越來越慢。',
 misconception:'催化劑和升溫只改變「反應多快」，不改變「最後生成多少」；產物的量由反應物的量決定。',safety:'真實實驗要戴護目鏡；不可自行混合家用清潔劑。',
 source:['OpenStax：影響反應速率的因素','https://openstax.org/books/chemistry-2e/pages/12-2-factors-affecting-reaction-rates'],related:[['../particle-reaction-lab.html','粒子與化學反應'],['solubility.html','溶解度與濃度']],
 quiz:[quiz('其他條件相同，把塊狀反應物磨成粉末，反應會？',['變慢','變快','不變'],1,'顆粒越細，接觸面積越大，碰撞機會越多。'),quiz('加入催化劑後，最後生成的產物總量？',['變多','變少','不變'],2,'看產物—時間曲線的終點高度。'),quiz('本頁「每升高 10°C 速率加倍」是？',['所有反應都成立的定律','粗略的經驗法則，本頁用來教學','催化劑的作用'],1,'真實反應升溫加快的程度各不相同。')]
 },
 {
 id:'reflection-refraction',noPrediction:true,title:'光的反射與折射實驗室',subject:'理化',grade:'國中',unit:'光學',minutes:'15–20',prior:'光的直線傳播、法線',
 description:'改變入射角與介質，比較反射角與折射角；再用平面鏡找出像的位置，理解角度都要從法線量起。',
 goals:['知道反射角等於入射角，角度從法線量起','比較光從空氣進入水或玻璃、以及反方向時的偏折方向','找出平面鏡成像的位置與性質，並認識全反射'],
 controls:[select('mode','現象',[['refraction','折射'],['mirror','平面鏡成像']],'refraction'),range('incident','入射角',0,85,5,30,'°'),select('media','介質（光從前者進入後者）',[['air-water','空氣→水（1→1.33）'],['air-glass','空氣→玻璃（1→1.5）'],['water-air','水→空氣（1.33→1）'],['glass-air','玻璃→空氣（1.5→1）']],'air-water'),range('dist','物體到鏡面距離（平面鏡）',5,50,5,20,'cm')],
 prediction:'這組設定下，光線會？',choices:[['normal','垂直入射，不偏折'],['toward','折射光偏向法線'],['away','折射光偏離法線'],['tir','全反射，沒有折射光'],['mirror','在平面鏡反射並成像']],
 tasks:[task('① 空氣進入水',{mode:'refraction',incident:30,media:'air-water'},'入射角 30°，折射角比入射角大還是小？角度從哪條線量起？'),task('② 方向反過來',{mode:'refraction',incident:30,media:'water-air'},'只把方向改成水→空氣，同樣 30°，折射光偏向還是偏離法線？'),task('③ 玻璃進入空氣',{mode:'refraction',incident:40,media:'glass-air'},'把入射角從 40° 慢慢加到 45°，折射光到哪裡去了？')],
 guide:[{say:'先看光從空氣射入水中，入射角 30°。',check:{q:'折射光？',from:'kind',options:[['toward','偏向法線'],['away','偏離法線'],['tir','全反射']]},hint:'比較折射角和入射角。',explain:'進入折射率較大的水，光偏向法線，折射角 22.1°。'},
  {say:'方向反過來：光從水射入空氣。',values:{},focus:'media',target:'water-air',check:{q:'折射光？',from:'kind',options:[['toward','偏向法線'],['away','偏離法線'],['tir','全反射']]},hint:'看讀值「偏折方向」。',explain:'進入折射率較小的空氣，光偏離法線。'},
  {say:'改成玻璃射入空氣，把入射角加到 45°。',values:{media:'glass-air'},focus:'incident',target:45,check:{q:'這時會？',from:'kind',options:[['toward','偏向法線'],['away','偏離法線'],['tir','全反射']]},hint:'看讀值「臨界角」。',explain:'入射角超過臨界角 41.8°，沒有折射光，全部反射回玻璃。'},
  {say:'換成平面鏡。',values:{},focus:'mode',target:'mirror',check:{q:'反射角是多少？',from:'reflection',options:[['30','30°'],['60','60°'],['90','90°']]},hint:'角度都從法線量起。',explain:'反射角＝入射角＝30°。'}],
 formula:'反射：反射角＝入射角。折射：n₁ sinθ₁＝n₂ sinθ₂（θ 皆從法線量起）。n₁ sinθ₁／n₂＞1 時沒有折射光，發生全反射；臨界角 θc＝sin⁻¹(n₂／n₁)。平面鏡：像距＝物距，正立、等大、虛像、左右相反。',
 limits:'單色光、界面平滑；折射率為教學常用值（水 1.33、玻璃 1.5、空氣 1），不計色散與吸收。折射時的部分反射只畫出方向，不計算亮度比例。全反射屬進階內容。平面鏡為理想平面，圖中比例為示意。',
 misconception:'入射角是光線和法線的夾角，不是光線和鏡面（界面）的夾角。',safety:'不可用雷射筆照射自己或他人的眼睛，也不要對著鏡子反射到別人臉上。',
 source:['OpenStax：折射定律','https://openstax.org/books/college-physics-2e/pages/25-3-the-law-of-refraction'],related:[['optics.html','光學與透鏡成像'],['../lenses.html','透鏡基礎教室']],
 quiz:[quiz('入射光與鏡面夾 60°，入射角是？',['60°','30°','120°'],1,'入射角從法線量起：90°−60°＝30°。'),quiz('光從空氣斜射進入水中，折射角會？',['大於入射角','小於入射角','等於入射角'],1,'進入折射率較大的介質，折射光偏向法線。'),quiz('平面鏡所成的像是？',['倒立實像','正立、等大、虛像','放大實像'],1,'像在鏡子後方，由反射光的反向延長線交會而成。')]
 },
 {
 id:'atom-builder',noPrediction:true,title:'原子結構與週期表實驗室',subject:'理化',grade:'國中',unit:'原子結構',minutes:'15–20',prior:'原子、質子、中子、電子',
 description:'調整質子、中子、電子的數目，看元素、質量數、電荷與電子層怎麼改變；分清楚離子和同位素差在哪裡。',
 goals:['說明元素種類只由質子數決定','由質子數與中子數求質量數，由質子數與電子數判斷電荷','區分離子（電子數改變）與同位素（中子數不同）'],
 controls:[range('p','質子數',1,20,1,11,'個'),range('n','中子數',0,22,1,12,'個'),range('e','電子數',0,20,1,11,'個')],
 prediction:'這組粒子組成的是？',choices:[['neutral','電中性原子'],['cation','陽離子（帶正電）'],['anion','陰離子（帶負電）']],
 tasks:[task('① 做出鈉原子',{p:11,n:12,e:11},'先記下鈉原子，再只把電子數改成 10：它變成什麼？元素變了嗎？'),task('② 只改中子數',{p:6,n:6,e:6},'從碳原子開始，只把中子數改成 8：元素變了嗎？哪個數字變了？'),task('③ 只改質子數',{p:12,n:12,e:11},'和任務①的鈉相比只多一個質子：現在是什麼元素？週期表上的紅框移到哪裡？')],
 guide:[{say:'先看預設：11 個質子、12 個中子、11 個電子。',check:{q:'這是什麼元素？',from:'symbol',options:[['Na','鈉 Na'],['Mg','鎂 Mg'],['Ne','氖 Ne']]},hint:'看右邊週期表上的紅框。',explain:'質子數 11 決定它是鈉。'},
  {say:'只改電子數：把電子改成 10 個。',values:{},focus:'e',target:10,check:{q:'現在的電荷是？',from:'charge',options:[['0','0（電中性）'],['1','＋1'],['-1','－1']]},hint:'看讀值「電荷」：質子數減電子數。',explain:'電子少一個，變成帶 ＋1 的鈉離子 Na⁺；質子沒變，所以還是鈉。'},
  {say:'電子回到 11 個，這次只改中子：把中子改成 13 個。',values:{},focus:'n',target:13,check:{q:'質量數是多少？',from:'A',options:[['23','23'],['24','24'],['12','12']]},hint:'質量數＝質子數＋中子數。',explain:'11＋13＝24。質子數沒變，所以仍是鈉；只有中子數不同，這就是同位素的概念。'},
  {say:'最後只改質子：把質子改成 12 個。',values:{},focus:'p',target:12,check:{q:'現在是什麼元素？',from:'symbol',options:[['Na','鈉 Na'],['Mg','鎂 Mg'],['Al','鋁 Al']]},hint:'看週期表上的紅框移到哪一格。',explain:'質子數變成 12，就變成鎂；決定元素的只有質子數。'}],
 formula:'質量數 A＝質子數＋中子數；電荷＝質子數－電子數；前 20 號元素的電子依 2、8、8、2 由內往外填入電子層。',
 limits:'同心圓（波耳）模型是簡化模型，電子不是沿固定軌道繞行。只處理前 20 號元素；電子層依 2、8、8、2 填入，不討論更外層。常見同位素表只列課本常見的組合，不在表內者標示「非常見組合，本頁不判斷是否穩定」。電荷超過 ±3 的離子在國中不會出現，本頁只作數字練習。',
 misconception:'決定「是什麼元素」的只有質子數；改電子數得到離子，改中子數得到同位素。',safety:'本頁為模型操作；鈉、鉀等活性金屬在真實實驗中遇水會劇烈反應，不可自行取用。',
 source:['OpenStax：原子結構與符號','https://openstax.org/books/chemistry-2e/pages/2-3-atomic-structure-and-symbolism'],related:[['../particle-reaction-lab.html','粒子與化學反應'],['reaction-rate.html','反應速率']],
 quiz:[quiz('把原子的一個電子拿走，會變成？',['另一種元素','帶正電的陽離子','同位素'],1,'元素由質子數決定；電子變少，電荷變正。'),quiz('C-12 與 C-14 的差別是？',['質子數不同','中子數不同','電子數不同'],1,'把質子數設為 6，只改中子數試試。'),quiz('質子數從 11 變成 12，會？',['變成另一種元素','只變成離子','只變成同位素'],0,'看週期表上的紅框移到哪一格。')]
 },
 {
 id:'stoichiometry',noPrediction:true,title:'莫耳與化學計量實驗室',subject:'理化',grade:'國中',unit:'化學計量',minutes:'15–20',prior:'原子量、分子量、化學反應式',
 description:'選一個反應，放入兩種反應物的質量，換算成莫耳數，找出誰先用完、生成多少產物，並核對反應前後總質量。',
 goals:['用「質量÷式量」求莫耳數','依係數比找出限量試劑，求產物質量與剩餘量','用數據說明反應前後總質量相等（質量守恆）'],
 controls:[select('reaction','反應',[['h2o','2H₂＋O₂ → 2H₂O'],['mgo','2Mg＋O₂ → 2MgO'],['caco3','CaCO₃＋2HCl → CaCl₂＋H₂O＋CO₂'],['nh3','N₂＋3H₂ → 2NH₃']],'h2o'),range('massA','第一種反應物質量',0,100,0.1,4,'g'),range('massB','第二種反應物質量',0,100,0.1,32,'g')],
 prediction:'這兩種反應物放在一起，會？',choices:[['none','缺少反應物，不發生反應'],['exact','恰好完全反應'],['limitA','第一種反應物先用完'],['limitB','第二種反應物先用完']],
 tasks:[task('① 氫與氧',{reaction:'h2o',massA:4,massB:32},'4 g 氫加 32 g 氧：生成多少水？有沒有剩下的反應物？'),task('② 只改氧的質量',{reaction:'h2o',massA:4,massB:16},'只把氧改成 16 g：水也變成一半嗎？剩下的是誰、剩多少？'),task('③ 質量一樣多',{reaction:'h2o',massA:10,massB:10},'兩種反應物都是 10 g，莫耳數也一樣嗎？誰先用完？')],
 guide:[{say:'先看：4 g 氫和 32 g 氧反應生成水。',check:{q:'兩者會？',from:'kind',options:[['exact','恰好完全反應'],['limitA','氫先用完'],['limitB','氧先用完']]},hint:'把質量換成莫耳數，再除以係數比較。',explain:'氫 2 mol÷2＝1，氧 1 mol÷1＝1，兩者相等，恰好完全反應。'},
  {say:'只把氧改成 16 g。',values:{},focus:'massB',target:16,check:{q:'誰先用完？',from:'kind',options:[['exact','同時用完'],['limitA','氫先用完'],['limitB','氧先用完']]},hint:'看讀值「限量試劑」。',explain:'氧只剩 0.5 mol，比氫少，氧是限量試劑。'},
  {say:'同樣 4 g 氫、16 g 氧，看剩下多少。',values:{massB:16},check:{q:'剩下的氫是多少？',from:'leftA',options:[['2','2 g'],['0','0 g'],['4','4 g']]},hint:'看讀值「剩餘反應物」。',explain:'只有一半的氫參加反應，剩下 2 g；反應前後總質量仍相等。'},
  {say:'氧回到 32 g，把氫加到 10 g。',values:{},focus:'massA',target:10,check:{q:'誰先用完？',from:'kind',options:[['exact','同時用完'],['limitA','氫先用完'],['limitB','氧先用完']]},hint:'比較兩者的莫耳數÷係數。',explain:'氫變多了，這次是氧先用完；係數比是莫耳數比，不是質量比。'}],
 formula:'莫耳數＝質量÷式量。反應物的莫耳數各自除以係數，較小的就是限量試劑；產物莫耳數＝限量試劑莫耳數÷其係數×產物係數；質量＝莫耳數×式量。原子量：H 1、C 12、N 14、O 16、Mg 24、Cl 35.5、Ca 40。',
 limits:'反應一定完全進行到限量試劑用完，不考慮可逆反應、副反應與產率；物質皆為純物質。質量以 0.1 g 為單位，判斷「恰好完全反應」時用整數比較，不受小數誤差影響。氣體只算質量，不討論體積。',
 misconception:'係數比是粒子數（莫耳數）比，不是質量比；質量一樣多，莫耳數不一定一樣多。',safety:'本頁為計算模擬；氫氣與氧氣混合遇火會爆炸，實驗室製備與收集需依教師指導。',
 source:['OpenStax：反應化學計量','https://openstax.org/books/chemistry-2e/pages/4-3-reaction-stoichiometry'],related:[['atom-builder.html','原子結構與週期表'],['../particle-reaction-lab.html','粒子與化學反應']],
 quiz:[quiz('2H₂＋O₂ → 2H₂O 中，係數比 2：1 代表？',['質量比 2：1','莫耳數（粒子數）比 2：1','體積一定是 2：1 公升'],1,'把氫和氧都設成 10 g，比較兩者的莫耳數。'),quiz('4 g 氫與 16 g 氧反應，先用完的是？',['氫','氧','同時用完'],1,'看讀值的「限量試劑」。'),quiz('反應後的總質量與反應前相比？',['變少','變多','相等'],2,'看圖下方的總質量核對。')]
 },
 {
 id:'weather-systems',noPrediction:true,title:'天氣系統實驗室',subject:'地科',grade:'國中',unit:'天氣與氣候',minutes:'15–20',prior:'氣壓、空氣的上升與下沉',
 description:'切換北半球與南半球的高氣壓、低氣壓與颱風，看近地面風怎麼轉、中心空氣往上還是往下；再比較冷鋒、暖鋒與滯留鋒過境前後的天氣。',
 goals:['說出北、南半球高低氣壓近地面的風向','連結中心的上升或下沉氣流與晴雨','比較冷鋒、暖鋒、滯留鋒的雲、降雨與過境後氣溫變化'],
 controls:[select('mode','觀察',[['pressure','高低氣壓'],['front','鋒面']],'pressure'),select('hemi','半球',[['north','北半球'],['south','南半球']],'north'),select('system','氣壓系統',[['high','高氣壓'],['low','低氣壓'],['typhoon','颱風']],'low'),select('front','鋒面',[['cold','冷鋒'],['warm','暖鋒'],['stationary','滯留鋒']],'cold'),select('phase','鋒面過境',[['before','過境前'],['during','過境中'],['after','過境後']],'during')],
 prediction:'目前觀察的是？',choices:[['high','高氣壓'],['low','低氣壓'],['typhoon','颱風（強烈的熱帶低氣壓）'],['cold','冷鋒'],['warm','暖鋒'],['stationary','滯留鋒']],
 tasks:[task('① 北半球低氣壓',{mode:'pressure',hemi:'north',system:'low'},'近地面的風怎麼轉？往中心吹進去還是往外吹出來？中心的空氣往上還是往下？'),task('② 只改成南半球',{mode:'pressure',hemi:'south',system:'low'},'只改半球，旋轉方向和往內往外各有沒有變？'),task('③ 比較冷鋒與暖鋒',{mode:'front',front:'cold',phase:'after'},'記下冷鋒過境後的氣溫變化，再只把鋒面改成暖鋒，變化方向為什麼相反？')],
 formula:'北半球：高氣壓順時針向外吹出、中心下沉；低氣壓逆時針向中心吹入、中心上升。南半球旋轉方向相反，往內往外不變。颱風是強烈的熱帶低氣壓。冷鋒：冷氣團推向暖氣團，積雨雲、雨勢急而短，過境後降溫；暖鋒：暖氣團爬上冷氣團，層狀雲、雨勢緩而久，過境後升溫；滯留鋒：冷暖氣團勢力相當，長時間降雨（臺灣梅雨）。',
 limits:'定性模型：只呈現風向、氣流與天氣的典型型態，不計算風速、氣壓數值與移動速度。近地面風向與等壓線的夾角固定畫約 30°，真實夾角隨地面摩擦而變。鋒面剖面的坡度只是示意；實際天氣會受地形與季節影響。',
 misconception:'風不是直接從高壓吹向低壓；地球自轉使風向偏轉，所以繞著氣壓中心旋轉。',safety:'颱風或豪雨期間請依中央氣象署與地方政府的警報行動，不要到海邊、河邊或山區。',
 source:['NOAA JetStream：地面天氣圖與鋒面','https://www.noaa.gov/jetstream/wxmaps'],related:[['seasons.html','四季與太陽高度'],['../plate-earthquake-lab.html','板塊與地震']],
 quiz:[quiz('北半球低氣壓近地面的風是？',['順時針向外吹出','逆時針向中心吹入','直接從四周直線吹向中心'],1,'選北半球低氣壓，看俯視圖上的箭頭。'),quiz('高氣壓中心的天氣通常比較晴朗，因為？',['空氣上升形成雲','空氣下沉不易成雲','風很大把雲吹走'],1,'看右邊剖面圖中心的氣流方向。'),quiz('冷鋒過境後，氣溫通常會？',['上升','下降','不變'],1,'把鋒面設成冷鋒、過境後，讀「過境後氣溫」。')]
 },
 {
 id:'circulation',noPrediction:true,title:'血液循環實驗室',subject:'生物',grade:'國中',unit:'運輸作用',minutes:'15–20',prior:'心臟四個腔室、動脈與靜脈',
 description:'沿著血液走一圈：先到肺還是先到全身？選一條血管看裡面是充氧血還是缺氧血；再調高運動強度，比較心跳與心輸出量增加多少。',
 goals:['依序說出體循環與肺循環的路徑','判斷四條主要血管屬於哪個循環、流的是充氧血或缺氧血','說明動脈與靜脈是依血流方向命名，不是依含氧多寡'],
 controls:[range('intensity','運動強度',0,100,10,0,'%'),select('site','觀察的血管',[['pa','肺動脈'],['pv','肺靜脈'],['aorta','主動脈'],['vc','大靜脈']],'pa')],
 prediction:'目前選的血管裡流的是？',choices:[['oxygenated','充氧血'],['deoxygenated','缺氧血']],
 tasks:[task('① 走一圈',{intensity:0,site:'vc'},'從大靜脈出發，沿著箭頭走：血液先回到心臟的哪一側？接著先到肺還是先到全身？'),task('② 只看肺動脈',{intensity:0,site:'pa'},'它叫「動脈」，裡面流的是充氧血嗎？再切到肺靜脈比較。'),task('③ 用力運動',{intensity:100,site:'aorta'},'強度從 0% 調到 100%：心跳變成幾倍？每分鐘心輸出量變成幾倍？哪一個增加得多？')],
 formula:'每分鐘心輸出量（L／分）＝心跳（次／分）×每搏輸出量（mL）÷1000。本頁教學模型：心跳＝70＋1.1×強度，每搏輸出量＝70＋0.4×強度。',
 limits:'心跳與每搏輸出量的公式是教學用虛構數值，只用來比較「增加幾倍」，不是任何人的實際數值。循環圖是簡化示意，只畫四條主要血管與心臟四個腔室，不畫瓣膜與冠狀循環。藍色只是繪圖慣例，缺氧血實際是暗紅色。',
 misconception:'動脈、靜脈是依「離開或回到心臟」命名，不是依含氧多寡；肺動脈流的是缺氧血。',safety:'本頁為教學模型，數值不是醫療建議或運動處方；身體不適或運動時心跳異常請告知大人並就醫。',
 source:['OpenStax：哺乳類的心臟與血管','https://openstax.org/books/biology-2e/pages/40-3-mammalian-heart-and-blood-vessels'],related:[['plant-exchange.html','植物的氣體交換'],['../microscope-lab.html','顯微鏡實驗室']],
 quiz:[quiz('肺動脈裡流的是？',['充氧血','缺氧血','淋巴液'],1,'選肺動脈，看圖上它的顏色與讀值。'),quiz('血液從左心室出發，下一站是？',['肺臟','全身組織','右心房'],1,'選主動脈，沿著箭頭走。'),quiz('運動強度從 0% 到 100%，心輸出量大約變成幾倍？',['約 1.5 倍','約 2.6 倍','約 4 倍'],2,'心跳和每搏輸出量都增加，兩者相乘。')]
 },
 {
 id:'nerve-reflex',noPrediction:true,title:'神經與反應時間實驗室',subject:'生物',grade:'國中',unit:'協調作用',minutes:'15–20',prior:'受器、神經、動器',
 description:'比較膝跳反射、碰到燙的東西縮手、看到球後接住三種反應的神經路徑，找出哪些經過大腦判斷；再用接尺實驗算出自己的反應時間。',
 goals:['依序說出反應的路徑：受器→感覺神經→中樞→運動神經→動器','區分反射（中樞在脊髓）與經大腦判斷的反應','由接尺實驗的落下距離求反應時間'],
 controls:[select('action','動作',[['knee','膝跳反射'],['withdraw','手碰到燙的東西縮回'],['catch','看到球後接住']],'knee'),range('drop','接尺實驗：尺落下的距離',0,50,1,20,'cm')],
 prediction:'這個動作屬於？',choices:[['reflex','反射（中樞在脊髓，不經大腦判斷）'],['voluntary','經大腦判斷的反應']],
 tasks:[task('① 膝跳反射',{action:'knee',drop:20},'依編號走一遍路徑：有經過大腦嗎？中樞在哪裡？'),task('② 碰到燙的東西',{action:'withdraw',drop:20},'縮手之後才覺得痛，為什麼？找出圖上較晚才到大腦的那條虛線。'),task('③ 接尺實驗',{action:'catch',drop:20},'和同學做接尺實驗，把尺落下的距離輸入：反應時間是多少？重複三次取平均，再和接球的路徑比較。')],
 formula:'反應路徑：受器→感覺神經→中樞（脊髓或大腦）→運動神經→動器。接尺實驗：尺自由落下 d 公分所需時間 t＝√(2d／g)，d 換成公尺，g＝9.8 m/s²。',
 limits:'神經路徑為課本層級的簡化示意，不畫神經元與突觸細節；接球的路徑省略小腦等其他腦區。接尺實驗假設尺由靜止自由落下、不計空氣阻力，只量「看到放手到抓住」的時間，不是神經傳導的純時間。',
 misconception:'反射不是「沒有神經中樞」，而是中樞在脊髓（或腦幹），不需要大腦判斷。',safety:'做接尺實驗時，尺不可朝人揮動；做膝跳反射時請輕敲，不要用力。',
 source:['OpenStax：自由落體','https://openstax.org/books/college-physics-2e/pages/2-7-falling-objects'],related:[['circulation.html','血液循環'],['../microscope-lab.html','顯微鏡實驗室']],
 quiz:[quiz('膝跳反射的中樞在？',['大腦','脊髓','眼睛'],1,'選膝跳反射，看路徑中間那一站。'),quiz('碰到燙的東西，為什麼先縮手、後覺得痛？',['縮手的路徑不必先到大腦，痛覺要傳到大腦才產生','痛覺比較快','縮手是大腦先決定的'],0,'選縮手，比較實線路徑與較晚到大腦的虛線。'),quiz('接尺實驗中尺落下的距離越長，表示反應時間？',['越短','越長','一樣'],1,'把落下距離調大，看反應時間讀值。')]
 },
 {
 id:'homeostasis',noPrediction:true,title:'血糖與體溫恆定實驗室',subject:'生物',grade:'國中',unit:'恆定性',minutes:'15–20',prior:'激素、神經、血液循環',
 description:'吃進醣類或運動後，血糖怎麼偏離又被拉回來？胰島素分泌不足時有什麼不同？再切到體溫，看天冷天熱時身體怎麼保持 37°C。',
 goals:['說明血糖升高時胰島素、降低時升糖素的作用','比較胰島素正常與不足時血糖回穩的差別','說明天冷與天熱時皮膚血管、顫抖與流汗如何維持體溫'],
 controls:[select('mode','觀察',[['glucose','血糖'],['temp','體溫']],'glucose'),range('carb','進食的醣類',0,100,10,50,'g'),range('exercise','運動時間',0,60,10,0,'分'),select('insulin','胰島素分泌',[['normal','正常'],['low','不足']],'normal'),range('env','環境溫度',0,40,5,25,'°C')],
 prediction:'目前身體的狀態是？',choices:[['steady','血糖在正常範圍'],['high','血糖偏高，胰島素增加'],['low','血糖偏低，升糖素增加'],['cold','天冷，減少散熱、增加產熱'],['neutral','溫度適中，無明顯調節'],['hot','天熱，增加散熱']],
 tasks:[task('① 吃了 50 g 醣類',{mode:'glucose',carb:50,exercise:0,insulin:'normal'},'血糖升高之後為什麼會降回來？是哪一種激素在作用？'),task('② 胰島素不足',{mode:'glucose',carb:50,exercise:0,insulin:'low'},'只把胰島素改成不足，比較峰值和回穩時間。'),task('③ 空腹運動',{mode:'glucose',carb:0,exercise:60,insulin:'normal'},'沒有進食、運動 60 分鐘，血糖怎麼變？這時哪一種激素增加？')],
 formula:'教學模型：基準血糖 90；峰值＝90＋0.8×醣類（胰島素正常）或 90＋1.6×醣類（不足）；回到基準需 2 小時（正常）或 5 小時（不足）；運動後最低值＝90－0.5×運動分鐘數。高於 110 時胰島素增加，低於 80 時升糖素增加。體溫：核心體溫維持 37°C；環境低於 20°C 皮膚血管收縮、顫抖；高於 30°C 皮膚血管舒張、流汗。',
 limits:'所有數值都是虛構的教學數值，只用來說明「偏離後被拉回來」的方向，不能用於任何健康判斷。血糖曲線是簡化示意，進食與運動的影響分開畫，不代表真實時間變化。體溫只區分三個溫度範圍，不計算散熱量。',
 misconception:'恆定不是「數值固定不變」，而是偏離後會被拉回來。',safety:'本頁不是醫療建議；血糖或身體健康的問題請詢問醫師。',
 source:['OpenStax：恆定性','https://openstax.org/books/biology-2e/pages/33-3-homeostasis'],related:[['circulation.html','血液循環'],['nerve-reflex.html','神經與反應時間']],
 quiz:[quiz('飯後血糖升高，主要是哪一種激素讓它降回來？',['升糖素','胰島素','腎上腺素'],1,'設定進食 50 g，看讀值的「主要作用的激素」。'),quiz('胰島素分泌不足時，和正常相比？',['峰值較低、回穩較快','峰值較高、回穩較慢','完全一樣'],1,'只改胰島素，比較兩筆紀錄。'),quiz('天冷時，身體怎麼保持體溫？',['皮膚血管舒張、流汗','皮膚血管收縮、顫抖','體溫跟著下降'],1,'切到體溫，把環境溫度調到 10°C。')]
 },
 {
 id:'spring-friction',noPrediction:true,title:'彈簧與靜摩擦實驗室',subject:'理化',grade:'國中',unit:'力的測量',minutes:'15–20',prior:'力的單位、重力、摩擦力',
 description:'掛上砝碼看彈簧伸長多少，找出虎克定律；再用水平拉力拉木塊，看靜摩擦力怎麼跟著拉力變大，直到木塊開始滑動。',
 goals:['用 F＝kx 說明彈簧伸長量與外力成正比，並知道彈性限度','說明靜摩擦力會隨外力改變，直到最大靜摩擦','比較最大靜摩擦與動摩擦的大小'],
 controls:[select('mode','實驗',[['spring','彈簧伸長'],['block','拉動木塊']],'spring'),range('k','彈力常數',10,200,10,50,'N/m'),range('hang','吊掛質量',0,2,0.1,0.5,'kg'),range('limit','彈性限度伸長量',0.05,0.5,0.05,0.3,'m'),range('mass','木塊質量',0.5,10,0.5,2,'kg'),select('surface','接觸面',[['smooth','光滑木板（μs 0.3、μk 0.2）'],['rough','粗糙木板（μs 0.6、μk 0.4）'],['rubber','橡膠墊（μs 0.9、μk 0.7）']],'smooth'),range('pull','水平拉力',0,100,0.01,5,'N')],
 prediction:'目前的狀態是？',choices:[['within','彈簧在彈性限度內'],['over','彈簧超過彈性限度'],['rest','木塊靜止，靜摩擦力＝拉力'],['edge','木塊在臨界點（拉力＝最大靜摩擦）'],['moving','木塊滑動，受動摩擦力']],
 tasks:[task('① 質量加倍',{mode:'spring',k:50,hang:0.5,limit:0.3},'記下伸長量，再只把吊掛質量改成 1 kg：伸長量變成幾倍？'),task('② 拉了卻沒動',{mode:'block',mass:2,surface:'smooth',pull:2},'拉力 2 N 時木塊不動；改成 5 N 也不動。兩次的摩擦力一樣大嗎？'),task('③ 剛好要滑動',{mode:'block',mass:2,surface:'smooth',pull:5.88},'這是最大靜摩擦的臨界點。把拉力加到 6 N：摩擦力變大還是變小？')],
 guide:[{say:'先看彈簧：掛上 0.5 kg 的砝碼。',check:{q:'彈簧伸長多少？',from:'x',options:[['0.098','9.8 cm'],['0.196','19.6 cm'],['0.049','4.9 cm']]},hint:'看讀值「伸長量」。',explain:'4.9 N÷50 N/m＝0.098 m。'},
  {say:'只把質量加倍：改成 1 kg。',values:{},focus:'hang',target:1,check:{q:'伸長量變成？',from:'x',options:[['0.098','9.8 cm'],['0.196','19.6 cm'],['0.392','39.2 cm']]},hint:'看讀值「伸長量」。',explain:'在彈性限度內，伸長量和外力成正比。'},
  {say:'換成拉動木塊：2 kg 木塊在光滑木板上，用 5 N 拉。',values:{},focus:'mode',target:'block',check:{q:'木塊會？',from:'kind',options:[['rest','不動'],['edge','剛好要動'],['moving','滑動']]},hint:'比較拉力和最大靜摩擦。',explain:'5 N 小於最大靜摩擦 5.88 N，木塊不動，靜摩擦力也是 5 N。'},
  {say:'把拉力加到 10 N。',values:{mode:'block'},focus:'pull',target:10,check:{q:'木塊會？',from:'kind',options:[['rest','不動'],['edge','剛好要動'],['moving','滑動']]},hint:'看讀值「摩擦力」變成動摩擦還是靜摩擦。',explain:'超過最大靜摩擦就開始滑動，摩擦力變成較小的動摩擦 3.92 N。'}],
 formula:'彈簧：F＝kx（在彈性限度內），伸長量 x＝mg／k。木塊：正向力 N＝mg；最大靜摩擦 fs＝μs N。拉力小於 fs 時，靜摩擦力＝拉力、木塊不動；超過 fs 後改為動摩擦力 fk＝μk N，加速度 a＝(拉力－fk)／m。g＝9.8 m/s²。',
 limits:'接觸面的摩擦係數是教學值（光滑木板 μs 0.3、μk 0.2；粗糙木板 0.6、0.4；橡膠墊 0.9、0.7），不是實測值。拉力水平、木塊在水平面上，不計空氣阻力。彈簧超過彈性限度時仍顯示 F＝kx 的計算值，但虎克定律已不適用，真實彈簧可能永久變形。臨界點（拉力恰等於最大靜摩擦）可用任務③直接設定。',
 misconception:'靜摩擦力不是固定值；它等於外力，直到達到最大靜摩擦為止。',safety:'彈簧不要拉超過限度或突然放手讓它彈回；拉動重物時注意桌面邊緣，避免掉落。',
 source:['OpenStax：摩擦力','https://openstax.org/books/college-physics-2e/pages/5-1-friction'],related:[['../force-motion-lab.html','力與運動實驗室'],['lever-torque.html','槓桿與力矩']],
 quiz:[quiz('木塊沒有動，拉力從 2 N 加到 5 N，靜摩擦力？',['一直等於最大靜摩擦','跟著變成 5 N','變成 0'],1,'用任務②比較兩筆紀錄的摩擦力。'),quiz('在彈性限度內，彈簧掛的質量加倍，伸長量？',['加倍','不變','變成四倍'],0,'用任務①，只改吊掛質量。'),quiz('木塊剛開始滑動之後，摩擦力和最大靜摩擦相比？',['比較大','比較小','一樣大'],1,'看摩擦力—拉力圖在臨界點之後往下掉。')]
 },
 {
 id:'electric-power',noPrediction:true,title:'電流熱效應實驗室',subject:'理化',grade:'國中',unit:'電流熱效應',minutes:'15–20',prior:'電壓、電流、電阻、歐姆定律',
 description:'把電熱線放進水裡通電，比較電功率、電能與水溫上升；再比較「固定電壓」和「固定電流」時，電阻加倍的結果為什麼相反。',
 goals:['用 P＝IV 求電功率，用 E＝Pt 求電能','由電能與水的質量估算水溫上升','說明固定電壓與固定電流時，電阻對發熱的影響相反'],
 controls:[select('mode','比較條件',[['fixedV','固定電壓'],['fixedI','固定電流']],'fixedV'),range('volt','電壓（固定電壓時）',1,12,1,6,'V'),range('amp','電流（固定電流時）',0.5,3,0.5,1,'A'),range('ohm','電阻',1,50,1,6,'Ω'),range('time','通電時間',0,600,10,70,'s'),range('water','水的質量',50,500,50,100,'g'),range('loss','散失到環境',0,50,5,0,'%')],
 prediction:'目前的狀態是？',choices:[['idle','沒有通電（時間為 0）'],['heating','通電加熱中'],['boiling','水已加熱到沸點']],
 tasks:[task('① 讀功率與溫升',{mode:'fixedV',volt:6,ohm:6,time:70,water:100,loss:0},'電流、功率、電能各是多少？水溫上升幾度？'),task('② 固定電壓，電阻加倍',{mode:'fixedV',volt:6,ohm:12,time:70,water:100,loss:0},'只把電阻從 6 Ω 改成 12 Ω：功率變大還是變小？'),task('③ 固定電流，電阻加倍',{mode:'fixedI',amp:1,ohm:12,time:70,water:100,loss:0},'改成固定電流 1 A，同樣把電阻加倍：結論和任務②相反，為什麼？')],
 guide:[{say:'先看預設：6 V 電源接 6 Ω 電熱線。',check:{q:'電功率是多少？',from:'P',options:[['6','6 W'],['36','36 W'],['1','1 W']]},hint:'P＝V²÷R。',explain:'36÷6＝6 W。'},
  {say:'電壓固定，只把電阻加倍：12 Ω。',values:{},focus:'ohm',target:12,check:{q:'電功率變成？',from:'P',options:[['3','3 W'],['12','12 W'],['6','6 W']]},hint:'電壓固定時，電流會變小。',explain:'電壓固定時，電阻加倍，功率變成一半。'},
  {say:'改成電流固定 1 A，一樣把電阻調到 12 Ω。',values:{mode:'fixedI'},focus:'ohm',target:12,check:{q:'電功率變成？',from:'P',options:[['3','3 W'],['12','12 W'],['6','6 W']]},hint:'電流固定時用 P＝I²R。',explain:'電流固定時，電阻加倍，功率也加倍；和上一步相反。'},
  {say:'回到預設，只把通電時間加倍：140 秒。',values:{},focus:'time',target:140,check:{q:'水溫上升多少？',from:'dT',options:[['2','2 °C'],['1','1 °C'],['4','4 °C']]},hint:'看讀值「水溫上升」。',explain:'電能＝功率×時間，時間加倍，吸收的熱與溫升都加倍。'}],
 formula:'固定電壓：I＝V／R，P＝V²／R。固定電流：V＝IR，P＝I²R。電能 E＝Pt（J），1 度＝1 kWh＝3.6×10⁶ J。水溫上升 ΔT＝E×(1－散失比例)÷(水的質量×4.2)，水的比熱取 4.2 J/g·°C。',
 limits:'電熱線的電阻固定，不隨溫度改變；電源理想，電壓或電流不受負載影響。水的初溫設為 25°C，到 100°C 即標示「已達沸點」，本模型不處理沸騰與水的蒸發。散失比例為教學設定值。',
 misconception:'「電阻越大越熱」只在電流相同時成立；電壓相同時，電阻越小功率越大。',safety:'不可自行拆接家用插座或用電熱線加熱；本頁為模擬。',
 source:['OpenStax：電功率與電能','https://openstax.org/books/college-physics-2e/pages/20-4-electric-power-and-energy'],related:[['../circuit-lab.html','電路實驗室'],['energy.html','能量轉換與守恆']],
 quiz:[quiz('電壓固定時，把電阻加倍，電功率會？',['加倍','變成一半','不變'],1,'用任務②比較兩筆紀錄。'),quiz('電流固定時，把電阻加倍，電功率會？',['加倍','變成一半','不變'],0,'用任務③，P＝I²R。'),quiz('功率 6 W 通電 70 秒，電能是？',['76 J','420 J','11.7 J'],1,'E＝Pt。')]
 },
 {
 id:'electrostatics',noPrediction:true,title:'靜電與感應起電實驗室',subject:'理化',grade:'國中',unit:'靜電',minutes:'10–15',prior:'原子的構造、同性相斥異性相吸',
 description:'把帶電棒靠近放在絕緣座上的金屬球，比較只靠近、接地、兩種移開順序與接觸起電的結果；圖上只畫電子怎麼移動。',
 goals:['說明帶電棒靠近時金屬球兩端的電性（極化）','比較感應起電的兩種移開順序為什麼結果不同','區分感應起電與接觸起電最後的電性'],
 controls:[select('rod','帶電棒',[['neg','帶負電（塑膠棒摩擦毛皮）'],['pos','帶正電（玻璃棒摩擦絲綢）']],'neg'),select('step','操作程序',[['near','只靠近'],['ground','靠近並接地'],['g1','靠近接地 → 先移開接地 → 再移開帶電棒'],['g2','靠近接地 → 先移開帶電棒 → 再移開接地'],['contact','接觸後移開']],'near')],
 prediction:'操作完成後，金屬球？',choices:[['polarized','極化：淨電荷為 0，兩端帶異性電'],['grounded','接地中：帶與棒相反的電'],['opposite','感應起電：帶與棒相反的電'],['neutral','回到電中性'],['same','接觸起電：帶與棒相同的電']],
 tasks:[task('① 只靠近',{rod:'neg',step:'near'},'帶負電的棒只靠近：金屬球有沒有帶電？靠近棒的那一端和遠端各帶什麼電？'),task('② 兩種移開順序',{rod:'neg',step:'g1'},'先移開接地、再移開帶電棒，最後帶什麼電？再改成「先移開帶電棒」比較。'),task('③ 接觸起電',{rod:'neg',step:'contact'},'接觸後移開，金屬球最後帶什麼電？和任務②的感應起電差在哪？')],
 guide:[{say:'先看帶負電的塑膠棒只靠近金屬球。',check:{q:'金屬球的淨電荷？',from:'kind',options:[['polarized','0（只有極化）'],['same','帶負電'],['opposite','帶正電']]},hint:'看讀值「金屬球淨電荷」。',explain:'電子只在球內移動，總數沒變，所以淨電荷是 0。'},
  {say:'改成：靠近並接地，先移開接地、再移開塑膠棒。',values:{},focus:'step',target:'g1',check:{q:'最後金屬球？',from:'kind',options:[['opposite','帶正電'],['same','帶負電'],['neutral','不帶電']]},hint:'看電子經接地線往哪裡走。',explain:'電子先流到大地，斷開接地後回不來，所以帶正電。'},
  {say:'改成：先移開塑膠棒、再移開接地。',values:{},focus:'step',target:'g2',check:{q:'最後金屬球？',from:'kind',options:[['opposite','帶正電'],['same','帶負電'],['neutral','不帶電']]},hint:'接地還連著時，電子能不能回來？',explain:'接地還連著，電子又流回球，所以回到電中性。移開順序決定結果。'},
  {say:'最後改成：塑膠棒直接接觸金屬球再移開。',values:{},focus:'step',target:'contact',check:{q:'最後金屬球？',from:'kind',options:[['opposite','帶正電'],['same','帶負電'],['neutral','不帶電']]},hint:'接觸時電子從哪裡移到哪裡？',explain:'接觸時電子從棒移到球，球帶和棒相同的負電。'}],
 formula:'同性相斥、異性相吸。金屬中能移動的是電子：帶負電＝電子比質子多，帶正電＝電子比質子少。感應起電：帶電棒靠近並接地，電子經接地線移動；先斷接地再移開棒，導體帶與棒相反的電。接觸起電：電子在棒與導體之間直接轉移，導體帶與棒相同的電。',
 limits:'定性模型：圖中正、負號只表示電荷分布的方向與相對多寡，不是實際數量；只畫電子移動，正電荷（原子核）位置固定不動。金屬球放在絕緣座上，空氣乾燥、不漏電。帶電棒的電性依常見的摩擦組合：塑膠棒摩擦毛皮帶負電、玻璃棒摩擦絲綢帶正電。',
 misconception:'移動的只有電子；「帶正電」是電子變少，不是正電荷跑進來。',safety:'乾燥天氣做靜電實驗可能有輕微電擊；不要在電子產品旁或加油站附近做靜電實驗。',
 source:['OpenStax：導體與絕緣體（含感應起電）','https://openstax.org/books/college-physics-2e/pages/18-2-conductors-and-insulators'],related:[['electric-power.html','電流熱效應'],['../circuit-lab.html','電路實驗室']],
 quiz:[quiz('帶負電的棒只靠近金屬球（不接觸、不接地），金屬球的淨電荷是？',['帶正電','帶負電','0'],2,'用任務①，看讀值的「淨電荷」。'),quiz('感應起電要讓金屬球帶電，應該先移開哪一個？',['先移開帶電棒','先移開接地線','同時移開'],1,'比較「先移開接地」與「先移開帶電棒」兩種程序。'),quiz('物體帶正電，是因為？',['多了正電荷','少了電子','多了中子'],1,'圖上的正號從頭到尾都沒有移動。')]
 },
 {
 id:'equilibrium',noPrediction:true,title:'可逆反應與平衡實驗室',subject:'理化',grade:'國中',unit:'可逆反應',minutes:'15–20',prior:'化學反應、反應速率',
 description:'虛構的可逆反應 A（無色）⇌ B（有色）：觀察兩種物質的量怎麼變化後趨於平穩、改變溫度時顏色深淺怎麼變，再在平衡後加入 A 看平衡往哪裡移動。',
 goals:['說明化學平衡時正、逆反應速率相等，反應並沒有停止','由平衡常數 K 求平衡時 A、B 的量，並知道平衡不一定是兩邊一樣多','判斷溫度改變或加入反應物時平衡移動的方向'],
 controls:[range('a0','A 的初始量',0,10,1,10,'單位'),range('b0','B 的初始量',0,10,1,0,'單位'),select('temp','溫度',[['low','低（K＝0.5）'],['mid','中（K＝2）'],['high','高（K＝4）']],'mid'),range('add','達平衡後再加入 A',0,5,1,0,'單位')],
 prediction:'目前的狀態是？',choices:[['empty','沒有反應物'],['equilibrium','已達平衡'],['shifted','加入 A 後平衡移動，再次達到平衡']],
 tasks:[task('① 反應停了嗎？',{a0:10,b0:0,temp:'mid',add:0},'平衡時 A、B 各剩多少？曲線變平了，反應停了嗎？看下方正、逆反應速率。'),task('② 只改溫度',{a0:10,b0:0,temp:'high',add:0},'只把溫度改成高：試管顏色變深還是變淺？B 的比例變多少？'),task('③ 再加入 A',{a0:10,b0:0,temp:'mid',add:2},'平衡後再加入 2 單位 A：加進去的 A 全部變成 B 了嗎？')],
 guide:[{say:'先看：A 10 單位、B 0 單位，K＝2。',check:{q:'平衡時 B 大約是多少？',from:'B',round:2,options:[['6.67','6.67'],['5','5'],['10','10']]},hint:'平衡時 B÷A＝K。',explain:'總量 10，B 是 A 的 2 倍，所以 B≈6.67、A≈3.33；兩邊不一樣多。'},
  {say:'只提高溫度：K 變成 4。',values:{},focus:'temp',target:'high',check:{q:'平衡時 B 變成？',from:'B',options:[['8','8'],['6.67','6.67'],['10','10']]},hint:'看試管顏色和讀值。',explain:'本頁的正反應吸熱，升溫使 K 變大，B 變多、顏色變深。'},
  {say:'溫度回到中，平衡後再加入 2 單位 A。',values:{},focus:'add',target:2,check:{q:'重新平衡後 A 是多少？',from:'A',options:[['4','4'],['3.33','3.33'],['6','6']]},hint:'看曲線加入 A 之後的終點。',explain:'平衡向右移，但加入的 A 只有一部分變成 B，A 從 3.33 變成 4。'},
  {say:'改成從另一邊開始：A 0、B 10。',values:{a0:0,b0:10},check:{q:'平衡時 B 大約是多少？',from:'B',round:2,options:[['6.67','6.67'],['10','10'],['0','0']]},hint:'和第 1 步比較。',explain:'不論從哪一邊開始，同樣的 K 會到達同樣的平衡。'}],
 formula:'A ⇌ B，平衡時 B 的量÷A 的量＝K。總量 T＝A＋B（加入 A 後再加上加入量），平衡時 A＝T÷(1＋K)、B＝T×K÷(1＋K)。平衡時正反應速率＝逆反應速率。本頁的正反應吸熱：溫度越高，K 越大。',
 limits:'A ⇌ B 是虛構的教學反應，K 值（0.5、2、4）為教學設定；以「量」代替濃度，體積固定。曲線趨近平衡的形狀與時間只是示意，不代表真實反應快慢。只比較平衡狀態，不計算達到平衡所需的時間。',
 misconception:'平衡不是反應停止，也不是兩邊濃度相等，而是正、逆反應速率相等。',safety:'本頁為模擬；真實的可逆反應實驗（例如二氧化氮與四氧化二氮）氣體有毒，須在教師指導下於通風處進行。',
 source:['OpenStax：化學平衡','https://openstax.org/books/chemistry-2e/pages/13-1-chemical-equilibria'],related:[['reaction-rate.html','反應速率'],['stoichiometry.html','莫耳與化學計量']],
 quiz:[quiz('達到化學平衡時，反應？',['已經停止','仍在進行，正、逆反應速率相等','只剩正反應'],1,'用任務①看下方的正、逆反應速率。'),quiz('K＝2 時，平衡時 A 與 B 的量？',['一樣多','B 是 A 的 2 倍','A 是 B 的 2 倍'],1,'讀值中的 A、B 相除。'),quiz('從只有 B 開始（A＝0、B＝10），K＝2 的平衡結果和從只有 A 開始相比？',['完全相同','B 比較多','A 比較多'],0,'把初始量對調試試看。')]
 },
 {
 id:'metal-activity',noPrediction:true,title:'金屬氧化還原實驗室',subject:'理化',grade:'國中',unit:'氧化還原',minutes:'15–20',prior:'原子、離子、電子',
 description:'把金屬片放進不同的溶液，看哪些組合會析出金屬或產生氫氣；再從電子的轉移找出誰被氧化、誰被還原，排出金屬的活性順序。',
 goals:['由金屬片放入溶液的結果判斷金屬的活性大小','說明氧化是失去電子、還原是得到電子','排出 Mg、Zn、Fe、(H)、Cu、Ag 的活性順序'],
 controls:[select('metal','放入的金屬',[['mg','鎂 Mg'],['zn','鋅 Zn'],['fe','鐵 Fe'],['cu','銅 Cu'],['ag','銀 Ag']],'zn'),select('solution','溶液',[['mgso4','硫酸鎂'],['znso4','硫酸鋅'],['feso4','硫酸亞鐵'],['cuso4','硫酸銅'],['agno3','硝酸銀'],['hcl','稀鹽酸']],'cuso4')],
 prediction:'放進去之後會？',choices:[['displace','金屬片表面析出另一種金屬'],['hydrogen','產生氫氣（冒泡）'],['none','不反應'],['same','同一種金屬，不反應']],
 tasks:[task('① 鋅放入硫酸銅',{metal:'zn',solution:'cuso4'},'鋅片表面出現什麼？溶液顏色怎麼變？誰失去電子？'),task('② 反過來',{metal:'cu',solution:'znso4'},'銅片放入硫酸鋅，為什麼沒有反應？'),task('③ 哪些會冒泡？',{metal:'mg',solution:'hcl'},'把每一種金屬都放進稀鹽酸試試：哪些會產生氫氣？用結果排出活性順序。')],
 guide:[{say:'先看：鋅片放進硫酸銅溶液。',check:{q:'會發生什麼？',from:'kind',options:[['displace','鋅片表面析出銅'],['hydrogen','冒出氫氣'],['none','不反應']]},hint:'比較活性順序中 Zn 和 Cu 的位置。',explain:'鋅比銅活潑，鋅失去電子，銅離子得到電子析出銅。'},
  {say:'反過來：銅片放進硫酸鋅溶液。',values:{solution:'znso4'},focus:'metal',target:'cu',check:{q:'會發生什麼？',from:'kind',options:[['displace','析出鋅'],['hydrogen','冒出氫氣'],['none','不反應']]},hint:'看活性順序。',explain:'銅比鋅不活潑，搶不到電子給鋅離子，所以不反應。'},
  {say:'換成鋅片放進稀鹽酸。',values:{},focus:'solution',target:'hcl',check:{q:'會發生什麼？',from:'kind',options:[['displace','析出金屬'],['hydrogen','冒出氫氣'],['none','不反應']]},hint:'比較 Zn 和 (H) 的位置。',explain:'鋅比氫活潑，H⁺ 得到電子變成氫氣。'},
  {say:'同樣是稀鹽酸，改放銅片。',values:{solution:'hcl'},focus:'metal',target:'cu',check:{q:'會發生什麼？',from:'kind',options:[['displace','析出金屬'],['hydrogen','冒出氫氣'],['none','不反應']]},hint:'比較 Cu 和 (H) 的位置。',explain:'銅在氫的後面，不會和稀鹽酸反應。'}],
 formula:'活性順序：Mg ＞ Zn ＞ Fe ＞ (H) ＞ Cu ＞ Ag。金屬的活性比溶液中的陽離子大，才會反應：金屬失去電子成為離子（氧化），陽離子得到電子（還原）析出金屬；稀鹽酸中的 H⁺ 得到電子變成氫氣。',
 limits:'定性模型：只判斷會不會反應與產物，不計算反應快慢與析出量。溶液顏色只區分常見的藍色（Cu²⁺）與淺綠色（Fe²⁺），其餘視為無色。鐵一律以 Fe²⁺ 表示。',
 misconception:'「氧化」不一定要有氧；失去電子就是氧化，得到電子就是還原。',safety:'硝酸銀會把皮膚染黑；使用稀酸要戴護目鏡；本頁為模擬。',
 source:['OpenStax：化學反應的分類（含活性順序）','https://openstax.org/books/chemistry-2e/pages/4-2-classifying-chemical-reactions'],related:[['stoichiometry.html','莫耳與化學計量'],['equilibrium.html','可逆反應與平衡']],
 quiz:[quiz('鋅片放入硫酸銅溶液，被氧化的是？',['鋅','銅離子','硫酸根'],0,'看讀值的「被氧化」。'),quiz('銅片放入硫酸鋅溶液，會？',['析出鋅','產生氫氣','不反應'],2,'比較活性順序中 Cu 和 Zn 的位置。'),quiz('下列哪一種金屬放進稀鹽酸不會冒泡？',['鎂','鐵','銅'],2,'把三種金屬分別放進稀鹽酸試試。')]
 },
 {
 id:'cell-electrolysis',noPrediction:true,title:'電池與電解實驗室',subject:'理化',grade:'國中',unit:'電流的化學效應',minutes:'20–25',prior:'氧化還原、離子',
 description:'比較鋅銅電池與三種電解裝置：哪一極變輕或變重、產生什麼氣體、電子在導線上往哪走、溶液裡的離子怎麼移動。',
 goals:['說明鋅銅電池中鋅極（負極）變輕、銅極（正極）變重與電子流向','說出電解水時兩極的氣體與體積比','比較用碳棒與銅棒電解硫酸銅時溶液顏色的差別'],
 controls:[select('mode','裝置',[['cell','鋅銅電池'],['water','電解水'],['cuC','電解硫酸銅（碳棒）'],['cuCu','電解硫酸銅（銅棒）']],'cell'),range('amp','電流',0,2,0.1,1,'A'),range('time','時間',0,3600,5,965,'s')],
 prediction:'目前的狀態是？',choices:[['idle','沒有電流通過'],['running','有電流通過，兩極發生變化']],
 tasks:[task('① 鋅銅電池',{mode:'cell',amp:1,time:965},'哪一極變輕、哪一極變重？導線上的電子往哪裡走？'),task('② 電解水',{mode:'water',amp:1,time:965},'兩極各產生什麼氣體？體積比是多少？'),task('③ 碳棒與銅棒',{mode:'cuC',amp:1,time:965},'記下溶液顏色的變化，再改成銅棒電解硫酸銅：顏色變化為什麼不同？')],
 guide:[{say:'先看鋅銅電池：1 A 電流通過 965 秒。',check:{q:'鋅極的質量？',from:'negMass',options:[['-0.327','減少 0.327 g'],['0.3175','增加 0.3175 g'],['0','不變']]},hint:'看讀值「負極變化」。',explain:'鋅失去電子變成 Zn²⁺ 溶到溶液中，所以變輕。'},
  {say:'換成電解水。',values:{},focus:'mode',target:'water',check:{q:'負極產生的氫氣是多少 mol？',from:'h2',options:[['0.005','0.005 mol'],['0.0025','0.0025 mol'],['0.01','0.01 mol']]},hint:'看讀值「負極變化」。',explain:'負極的氫氣是正極氧氣的 2 倍，所以體積比 2：1。'},
  {say:'換成用銅棒電解硫酸銅。',values:{},focus:'mode',target:'cuCu',check:{q:'正極（銅棒）的質量？',from:'posMass',options:[['-0.3175','減少 0.3175 g'],['0.3175','增加 0.3175 g'],['0','不變']]},hint:'看讀值「正極變化」。',explain:'正極的銅溶出多少，負極就析出多少，所以溶液顏色不變。'},
  {say:'回到鋅銅電池，把電流調到 0。',values:{},focus:'amp',target:0,check:{q:'現在？',from:'kind',options:[['running','兩極照樣變化'],['idle','沒有變化']]},hint:'沒有電子通過會怎樣？',explain:'沒有電流就沒有電子轉移，兩極都不會改變。'}],
 formula:'通過的電子莫耳數＝電流×時間÷96500（進階）。鋅銅電池：鋅極 Zn → Zn²⁺＋2e⁻（負極、變輕），銅極 Cu²⁺＋2e⁻ → Cu（正極、變重）。電解水：負極產生氫氣、正極產生氧氣，體積比 2：1。電解硫酸銅：負極析出銅；碳棒時正極產生氧氣、溶液變淡，銅棒時正極的銅溶解、溶液顏色不變。',
 limits:'理想情況：電流全部用在電極反應，不計副反應與電阻發熱。電子的莫耳數與質量計算屬進階內容，基本觀察只看變輕變重、氣體與顏色。鋅銅電池以鹽橋連接兩杯溶液；電解時「正極、負極」指接電源的正、負極。',
 misconception:'電子不會游過溶液；溶液中導電靠的是離子移動，電子只在導線與電極上流動。',safety:'電解會產生可燃的氫氣；不可使用家用插座電源；本頁為模擬。',
 source:['OpenStax：電解','https://openstax.org/books/chemistry-2e/pages/17-7-electrolysis'],related:[['metal-activity.html','金屬氧化還原'],['electric-power.html','電流熱效應']],
 quiz:[quiz('鋅銅電池中，變輕的是？',['鋅極','銅極','兩極都不變'],0,'用任務①讀負極的變化。'),quiz('電解水時，負極與正極產生的氣體體積比是？',['1：2','2：1','1：1'],1,'用任務②，負極是氫氣。'),quiz('溶液中負責導電的是？',['電子','離子','水分子'],1,'看圖：溶液中只畫離子的移動箭頭。')]
 },
 {
 id:'specific-heat',noPrediction:true,title:'比熱比較實驗室',subject:'理化',grade:'國中',unit:'熱量與比熱',minutes:'10–15',prior:'熱量、溫度',
 description:'用同樣的熱源加熱兩種質量相同的物質，比較誰的溫度上升得多；再用比熱解釋海邊沙灘燙、海水涼的原因。',
 goals:['用 Q＝mcΔT 求溫度上升','說明吸收同樣的熱量，比熱小的物質溫度上升較多','用比熱解釋生活中的現象'],
 controls:[select('subA','物質甲',[['water','水（4.2）'],['alcohol','酒精（2.4）'],['sand','沙（0.8）'],['iron','鐵（0.45）'],['copper','銅（0.39）']],'water'),select('subB','物質乙',[['water','水（4.2）'],['alcohol','酒精（2.4）'],['sand','沙（0.8）'],['iron','鐵（0.45）'],['copper','銅（0.39）']],'iron'),range('mass','兩者質量',50,500,50,100,'g'),range('power','加熱功率（各自相同）',10,100,1,42,'W'),range('time','加熱時間',0,300,10,10,'s')],
 prediction:'吸收同樣的熱量，哪一個溫度上升得多？',choices:[['idle','還沒加熱'],['heating','加熱中，比熱小的升溫多'],['limit','液體已達沸點（本模型不處理相變）']],
 tasks:[task('① 水和鐵',{subA:'water',subB:'iron',mass:100,power:42,time:10},'同質量、同熱量，水和鐵誰升溫多？差幾倍？'),task('② 只改質量',{subA:'water',subB:'iron',mass:200,power:42,time:10},'兩者質量都加倍，溫度上升變成多少？'),task('③ 沙灘與海水',{subA:'water',subB:'sand',mass:100,power:42,time:60},'白天太陽照射，沙灘很燙、海水還涼，用這一頁的數據解釋。')],
 guide:[{say:'先看：水和鐵各 100 g，用同樣的熱源加熱 10 秒。',check:{q:'兩者各吸收多少熱量？',from:'Q',options:[['420','420 J'],['42','42 J'],['4200','4200 J']]},hint:'熱量＝功率×時間。',explain:'42 W×10 s＝420 J，兩者吸收一樣多。'},
  {say:'比較兩者的溫度上升。',values:{},check:{q:'鐵的溫升大約是水的幾倍？',from:'ratio',round:1,options:[['9.3','9.3 倍'],['1','一樣'],['0.1','0.1 倍']]},hint:'看讀值「溫升倍數」。',explain:'鐵的比熱小，吸收同樣的熱，溫度上升比水多很多。'},
  {say:'兩者質量都加倍：200 g。',values:{},focus:'mass',target:200,check:{q:'兩者吸收的熱量？',from:'Q',options:[['420','還是 420 J'],['840','變成 840 J']]},hint:'熱源和時間都沒變。',explain:'熱量沒變，但質量加倍，所以溫升都變成一半。'},
  {say:'回到 100 g，把物質乙換成沙。',values:{},focus:'subB',target:'sand',check:{q:'沙的溫升大約是水的幾倍？',from:'ratio',round:1,options:[['5.3','5.3 倍'],['9.3','9.3 倍'],['1','一樣']]},hint:'看讀值「溫升倍數」。',explain:'沙的比熱也比水小，所以白天沙灘燙、海水涼。'}],
 formula:'吸收熱量 Q＝功率×時間；溫度上升 ΔT＝Q÷(質量×比熱)。比熱單位 J/g·°C：水 4.2、酒精 2.4、沙 0.8、鐵 0.45、銅 0.39。初溫 20°C。',
 limits:'兩者吸收同樣的熱量，不計散失到環境與容器吸熱；比熱視為固定。水 100°C、酒精 78°C 以上會沸騰，本模型不處理相變，達沸點即停止計算並提示；物態變化請見熱與物態實驗室。',
 misconception:'吸收一樣多的熱，不代表升一樣多的溫度；比熱小的物質溫度變化大。',safety:'加熱酒精要遠離火源，並在通風處進行；本頁為模擬。',
 source:['OpenStax：溫度變化與熱容量','https://openstax.org/books/college-physics-2e/pages/14-2-temperature-change-and-heat-capacity'],related:[['../heat-phase-lab.html','熱與物態實驗室'],['electric-power.html','電流熱效應']],
 quiz:[quiz('同質量的水和鐵吸收同樣的熱量，誰升溫多？',['水','鐵','一樣多'],1,'用任務①讀兩者的溫度上升。'),quiz('質量加倍、熱量不變，溫度上升會？',['加倍','變成一半','不變'],1,'用任務②比較。'),quiz('海邊白天沙灘比海水燙，主要因為？',['沙的比熱比水小','沙吸收的熱比較多','水不會吸熱'],0,'比較水和沙的比熱。')]
 },
 {
 id:'neutralization',noPrediction:true,title:'酸鹼中和實驗室',subject:'理化',grade:'國中',unit:'酸鹼中和',minutes:'15–20',prior:'酸、鹼、pH、指示劑',
 description:'用氫氧化鈉滴定鹽酸，觀察 pH 怎麼隨滴入的體積改變、在當量點附近怎麼突然跳升，以及過量的是哪一種離子。',
 goals:['由 H⁺ 與 OH⁻ 的莫耳數判斷溶液是酸性、中性或鹼性','找出當量點的體積，觀察當量點附近 pH 的急遽變化','說明酚酞在滴定中的顏色變化'],
 controls:[select('ca','鹽酸濃度',[['0.01','0.01 M'],['0.05','0.05 M'],['0.1','0.1 M'],['0.5','0.5 M'],['1','1 M']],'0.1'),range('va','鹽酸體積',10,50,5,25,'mL'),select('cb','氫氧化鈉濃度',[['0.01','0.01 M'],['0.05','0.05 M'],['0.1','0.1 M'],['0.5','0.5 M'],['1','1 M']],'0.1'),range('vb','已滴入氫氧化鈉體積',0,100,0.5,0,'mL')],
 prediction:'目前溶液是？',choices:[['acidic','酸性（H⁺ 過量）'],['neutral','中性（恰好中和）'],['basic','鹼性（OH⁻ 過量）']],
 tasks:[task('① 前段',{ca:'0.1',va:25,cb:'0.1',vb:10},'從 0 mL 每次加 5 mL 到 20 mL，pH 變化大嗎？'),task('② 當量點附近',{ca:'0.1',va:25,cb:'0.1',vb:24},'從 24 mL 慢慢加到 26 mL，pH 怎麼變？酚酞什麼時候變色？'),task('③ 繼續滴',{ca:'0.1',va:25,cb:'0.1',vb:40},'當量點之後繼續滴，溶液裡多出來的是什麼離子？')],
 guide:[{say:'先看還沒滴入氫氧化鈉時：錐形瓶裡是 0.1 M 鹽酸 25 mL。',check:{q:'pH 大約是多少？',from:'pH',round:0,options:[['1','1'],['7','7'],['13','13']]},hint:'看讀值「pH」。',explain:'鹽酸是強酸，0.1 M 時 pH＝1。'},
  {say:'打開活栓，把滴入的氫氧化鈉加到 20 mL。',values:{},focus:'vb',target:20,check:{q:'現在溶液是？',from:'kind',options:[['acidic','酸性'],['neutral','中性'],['basic','鹼性']]},hint:'看讀值「過量的離子」。',explain:'H⁺ 還比 OH⁻ 多，所以仍是酸性，pH 只升到約 2。'},
  {say:'慢慢滴，繼續加到 25 mL。',values:{vb:20},focus:'vb',target:25,check:{q:'pH 是多少？',from:'pH',round:0,options:[['4','4'],['7','7'],['10','10']]},hint:'看讀值「pH」，也看曲線上的紅點。',explain:'這是當量點：H⁺ 與 OH⁻ 恰好相等，pH＝7；注意曲線在這裡突然跳升。'},
  {say:'再多滴一點，加到 30 mL。',values:{vb:25},focus:'vb',target:30,check:{q:'酚酞變成什麼顏色？',from:'pink',options:[['false','無色'],['true','粉紅色']]},hint:'看錐形瓶的顏色或讀值「酚酞顏色」。',explain:'超過當量點後 OH⁻ 過量，溶液變鹼性，pH 大於 8.2，酚酞變粉紅色。'}],
 formula:'H⁺ 的莫耳數＝鹽酸濃度×體積；OH⁻ 的莫耳數＝氫氧化鈉濃度×滴入體積。H⁺ 過量：pH＝－log[H⁺]；恰好相等：pH＝7；OH⁻ 過量：pH＝14＋log[OH⁻]；濃度以混合後的總體積計算。當量點體積＝鹽酸莫耳數÷氫氧化鈉濃度。',
 limits:'25°C，強酸強鹼完全解離，不計水的解離（當量點附近 pH 變化因此特別陡）。相對導電度以溶液中離子總濃度表示，忽略各種離子移動快慢的差異。弱酸、弱鹼不在本頁範圍。',
 misconception:'中和到當量點時 pH 才等於 7，而且只在強酸配強鹼時成立；滴一點點鹼不會讓溶液馬上變中性。',safety:'強酸、強鹼有腐蝕性；稀釋時要把酸慢慢倒入水中，並戴護目鏡。',
 source:['OpenStax：酸鹼滴定','https://openstax.org/books/chemistry-2e/pages/14-7-acid-base-titrations'],related:[['../acid-base-indicator-lab.html','酸鹼指示劑實驗室'],['stoichiometry.html','莫耳與化學計量']],
 quiz:[quiz('0.1 M 鹽酸 25 mL，用 0.1 M 氫氧化鈉滴定，當量點在？',['10 mL','25 mL','50 mL'],1,'讀「當量點體積」。'),quiz('滴定過程中 pH 變化最大的地方在？',['剛開始','當量點附近','最後'],1,'用任務②觀察曲線。'),quiz('當量點之後繼續滴，溶液中過量的是？',['H⁺','OH⁻','Cl⁻'],1,'用任務③讀「過量的離子」。')]
 },
 {
 id:'cell-division',noPrediction:true,title:'細胞分裂實驗室',subject:'生物',grade:'國中',unit:'細胞分裂與生殖',minutes:'15–20',prior:'染色體、同源染色體',
 description:'一步一步看有絲分裂與減數分裂：染色體什麼時候複製、同源染色體什麼時候分開，最後各得到幾個細胞、每個細胞有幾條染色體。',
 goals:['說出有絲分裂與減數分裂各階段染色體的變化','比較兩種分裂最後的細胞數與染色體數','由 DNA 相對量的變化找出複製與分裂的時機'],
 controls:[select('type','分裂方式',[['mitosis','有絲分裂'],['meiosis','減數分裂']],'mitosis'),select('n2','母細胞染色體數',[['4','2n＝4'],['6','2n＝6'],['8','2n＝8']],'4'),range('stage','階段',0,5,1,0,'')],
 prediction:'目前細胞處在？',choices:[['interphase','間期（準備分裂）'],['dividing','分裂進行中'],['done','分裂完成']],
 tasks:[task('① 有絲分裂走一遍',{type:'mitosis',n2:'4',stage:0},'把階段從 0 調到 5：染色體數在哪一步暫時變成兩倍？最後幾個細胞、各幾條？'),task('② 減數分裂走一遍',{type:'meiosis',n2:'4',stage:0},'同樣從 0 調到 5：同源染色體在哪一步分開？最後每個細胞剩幾條？'),task('③ 比較結果',{type:'meiosis',n2:'6',stage:5},'改成 2n＝6，比較兩種分裂最後的細胞數與染色體數。')],
 formula:'有絲分裂：複製一次、分裂一次，得到 2 個細胞，染色體數與母細胞相同（2n）。減數分裂：複製一次、連續分裂兩次，得到 4 個細胞，染色體數減半（n）；第一次分裂時同源染色體分開，第二次分裂時姊妹染色分體分開。',
 limits:'示意模型：染色體以短棒表示，長度區分不同對，紅、藍區分來自母方與父方；間期的染色體實際上呈細絲狀，這裡為了計數仍畫成棒狀。減數分裂省略互換（交換）與不同的排列組合；細胞大小與形狀只是示意。',
 misconception:'減數分裂不是「分裂一次、染色體減半」，而是複製一次、連續分裂兩次。',safety:'本頁為模擬；製作洋蔥根尖玻片時，鹽酸與染色液要依教師指導使用。',
 source:['OpenStax：減數分裂','https://openstax.org/books/biology-2e/pages/11-1-the-process-of-meiosis'],related:[['../genetics-simulation-lab.html','遺傳模擬實驗室'],['../microscope-lab.html','顯微鏡實驗室']],
 quiz:[quiz('2n＝4 的細胞進行有絲分裂，最後得到？',['2 個細胞，各 4 條','4 個細胞，各 2 條','2 個細胞，各 2 條'],0,'用任務①走到階段 5。'),quiz('減數分裂中，同源染色體在哪一次分裂時分開？',['第一次','第二次','不會分開'],0,'用任務②看階段 3。'),quiz('減數分裂最後每個細胞的 DNA 量是複製後的？',['一半','四分之一','一樣'],1,'看右邊的 DNA 相對量。')]
 },
 {
 id:'enzyme',noPrediction:true,title:'酵素活性實驗室',subject:'生物',grade:'國中',unit:'酵素',minutes:'15–20',prior:'消化作用、蛋白質',
 description:'改變溫度、pH 與酵素的量，比較唾液澱粉酶與胃蛋白酶的活性；看看高溫變性後為什麼降溫也救不回來。',
 goals:['說明溫度與 pH 會影響酵素活性，並各有最適值','比較唾液澱粉酶與胃蛋白酶的最適 pH','說明高溫使酵素變性、形狀改變後無法恢復'],
 controls:[range('temp','溫度',0,80,1,37,'°C'),range('ph','pH',1,13,0.5,7,''),select('enzyme','酵素',[['amylase','唾液澱粉酶（最適 pH 7）'],['pepsin','胃蛋白酶（最適 pH 2）']],'amylase'),range('conc','酵素的量（相對）',0,5,0.5,1,'')],
 prediction:'在這個條件下，酵素的活性？',choices:[['active','活性高'],['low','活性低（條件回到最適時可恢復）'],['denatured','高溫變性（無法恢復）']],
 tasks:[task('① 最適溫度',{temp:37,ph:7,enzyme:'amylase',conc:1},'從 0°C 一路調到 80°C，活性在哪裡最高？超過 60°C 會怎樣？'),task('② 換成胃蛋白酶',{temp:37,ph:7,enzyme:'pepsin',conc:1},'同樣 37°C、pH 7，胃蛋白酶的活性為什麼很低？把 pH 調到 2 試試。'),task('③ 冷與熱的差別',{temp:0,ph:7,enzyme:'amylase',conc:1},'0°C 活性很低，70°C 也是 0；兩者有什麼不同？')],
 formula:'教學模型：相對活性＝溫度因子×pH 因子×酵素的量。溫度因子：0～37°C 由 0.05 升到 1，37～60°C 降到 0，60°C 以上變性為 0。pH 因子：以最適 pH 為中心的鐘形曲線（唾液澱粉酶 pH 7、胃蛋白酶 pH 2）。',
 limits:'曲線形狀與數值都是教學用虛構值，只呈現「有最適值」「高溫變性」的方向；真實酵素的最適溫度與 pH 各不相同。假設受質充足，所以活性與酵素的量成正比。本頁不記錄加熱歷程：溫度 60°C 以上一律顯示變性，說明中提醒降溫不會恢復。',
 misconception:'低溫只讓酵素變慢，回溫就能恢復；高溫會讓酵素變性，降溫也回不來。',safety:'做唾液澱粉酶實驗時使用自己的唾液、器材不共用；加熱時小心燙傷。',
 source:['OpenStax：酵素','https://openstax.org/books/biology-2e/pages/6-5-enzymes'],related:[['homeostasis.html','血糖與體溫恆定'],['../photosynthesis-factor-lab.html','光合作用因子實驗室']],
 quiz:[quiz('唾液澱粉酶在下列哪個溫度活性最高？',['0°C','37°C','70°C'],1,'用任務①從 0°C 調到 80°C。'),quiz('胃蛋白酶在 pH 7 的環境活性很低，因為？',['溫度太低','它的最適 pH 約為 2','酵素太少'],1,'用任務②把 pH 調到 2 比較。'),quiz('酵素在 70°C 失去活性後，降回 37°C 會？',['恢復活性','仍然沒有活性','活性加倍'],1,'高溫使酵素變性，形狀改變了。')]
 },
 {
 id:'tides',noPrediction:true,title:'潮汐實驗室',subject:'地科',grade:'國中',unit:'潮汐',minutes:'10–15',prior:'月相、萬有引力',
 description:'改變月齡與一天中的時刻，看月球的引力怎麼讓海水隆起、一天為什麼有兩次滿潮，以及大潮、小潮與月相的關係。',
 goals:['說明一天約有兩次滿潮、兩次乾潮','說明新月與滿月時是大潮、上弦與下弦時是小潮','知道每天的滿潮時間大約往後延 50 分鐘'],
 controls:[range('day','月齡（農曆日數，0＝新月）',0,29.5,0.5,0,'天'),range('hour','一天中的時刻',0,24,0.5,0,'時')],
 prediction:'這一天的潮差屬於？',choices:[['spring','大潮（潮差大）'],['middle','中潮'],['neap','小潮（潮差小）']],
 tasks:[task('① 一天兩次滿潮',{day:0,hour:0},'把時刻從 0 調到 24：這一天有幾次滿潮？間隔大約多久？'),task('② 大潮與小潮',{day:0,hour:0},'記下新月的潮差，再把月齡改成 7.5（上弦）：潮差變大還是變小？為什麼？'),task('③ 滿潮每天往後延',{day:1,hour:0},'比較月齡 0 與月齡 1 的下一次滿潮時間，差了多少？')],
 formula:'簡化的半日潮：潮高＝潮差因子×cos（2π×(時刻－延遲)÷12.42）。滿潮間隔約 12 小時 25 分；每過一天延遲約 50 分鐘。潮差因子＝0.6＋0.4×|cos(2π×月齡÷29.5)|：新月、滿月（太陽、月球、地球大致成一直線）時最大，上弦、下弦時最小。',
 limits:'簡化模型：只考慮月球與太陽的引潮力方向，不計海岸地形、海底深度與季節；各地實際的潮汐型態（半日潮、全日潮、混合潮）與時間都不同。潮高以相對值表示，不是實際公尺數；本頁不能當作潮汐預報。',
 misconception:'潮汐不是只有月球吸住面向它的海水；背對月球的一側也會隆起，所以一天有兩次滿潮。',safety:'到海邊活動前請查中央氣象署的潮汐預報，漲潮時不要在潮間帶或沙洲逗留。',
 source:['OpenStax：海洋潮汐與月球','https://openstax.org/books/astronomy-2e/pages/4-6-ocean-tides-and-the-moon'],related:[['moon-eclipse.html','月相、日食與月食'],['seasons.html','四季與太陽高度']],
 quiz:[quiz('一天大約有幾次滿潮？',['1 次','2 次','4 次'],1,'用任務①把時刻從 0 調到 24。'),quiz('大潮發生在？',['新月與滿月','上弦與下弦','每天中午'],0,'比較月齡 0、7.5、15 的潮差。'),quiz('為什麼背對月球的一側也會滿潮？',['那裡的海水被太陽吸住','地球被拉離那裡的海水，海水相對隆起','那裡沒有重力'],1,'看上方的俯視圖，海水在兩側都隆起。')]
 }
];
