// P1: embed a screen-only palette in the existing single-file worksheets.
// Original HTML, scripts, layout declarations and @media print stay byte-for-byte intact.
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {JSDOM} from 'jsdom';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const index=new JSDOM(fs.readFileSync(path.join(root,'tools/math/index.html'),'utf8'));
const cardCount=index.window.document.querySelectorAll('a.card').length;
const files=[...new Set([...index.window.document.querySelectorAll('a.card')].map(a=>new URL(a.getAttribute('href'),'https://www.bhcs.com.tw/tools/math/').pathname.slice(1)))].sort();
index.window.close();
const colors={green:'#16233A',green2:'#0D1626',mint:'#C8352B',soft:'#F2F4F7',line:'#C9D2DE',ink:'#16233A',muted:'#43516B',bg:'#FCFCFA',red:'#C8352B'};
const aliases={green:'green',green2:'green2',mint:'mint',blue:'green',deep:'green2',accent:'green',soft:'soft',line:'line',ink:'ink',muted:'muted',bg:'bg',red:'red',ans:'red'};
const block=/\n<style id="bhcs-math-brand">[\s\S]*?<\/style>\n/g;
function palette(r,g,b){
 const hi=Math.max(r,g,b),lo=Math.min(r,g,b);
 if(hi===lo)return null; // Keep black/white/neutral worksheet ink.
 if(hi-lo<12&&hi>240)return colors.bg;
 if(lo>=175&&hi>=225)return colors.soft;
 if(lo>=125&&hi>=185)return colors.line;
 if(r>g*1.25&&r>b*1.2)return colors.red;
 if(hi-lo<45&&hi>75&&hi<190)return colors.muted;
 return colors.ink;
}
function recolor(value){
 return value.replace(/#([\da-f]{8}|[\da-f]{6}|[\da-f]{4}|[\da-f]{3})\b/gi,(all,hex)=>{
  if(hex.length<5)hex=[...hex].map(c=>c+c).join('');
  const result=palette(...[0,2,4].map(i=>parseInt(hex.slice(i,i+2),16)));
  return result?result+(hex.length===8?hex.slice(6):''):all;
 }).replace(/rgba?\(\s*(\d+)[ ,]+(\d+)[ ,]+(\d+)([^)]*)\)/g,(all,r,g,b,alpha)=>{
  const result=palette(+r,+g,+b);if(!result)return all;
  const rgb=[1,3,5].map(i=>parseInt(result.slice(i,i+2),16));
  return alpha.trim().startsWith(',')?`rgba(${rgb.join(',')}${alpha})`:`rgb(${rgb.join(' ')}${alpha})`;
 });
}
function rules(list){
 const out=[];
 for(const rule of list){
  if(rule.cssRules){
   if(rule.conditionText&&/print/.test(rule.conditionText))continue;
   const inner=rules(rule.cssRules);if(inner)out.push(rule.cssText.slice(0,rule.cssText.indexOf('{')+1)+inner+'}');
  }else if(rule.selectorText&&rule.style){
   const declarations=[];
   for(let i=0;i<rule.style.length;i++){
    const prop=rule.style[i],value=rule.style.getPropertyValue(prop);let next=value;
    if(prop.startsWith('--')){
     const key=prop.replace(/^--bhcs-/,'').replace(/^--/,'');
     if(aliases[key])next=colors[aliases[key]];else next=recolor(value);
    }else if(prop==='border-radius')next='6px';
    else if(/^(color|background(?:-color|-image)?|border(?:-.+)?|outline(?:-.+)?|box-shadow|text-shadow|accent-color|fill|stroke)$/.test(prop))next=recolor(value);
    if(next!==value)declarations.push(`${prop}:${next}${rule.style.getPropertyPriority(prop)?'!important':''}`);
   }
   if(declarations.length)out.push(rule.selectorText+'{'+declarations.join(';')+'}');
  }
 }
 return out.join('\n');
}
for(const file of files){
 const target=path.join(root,file),original=fs.readFileSync(target,'utf8').replace(block,'');
 const dom=new JSDOM(original),d=dom.window.document;
 let css=[...d.styleSheets].map(s=>rules(s.cssRules)).filter(Boolean).join('\n');
 const svgColors=[...new Set(original.match(/#[\da-f]{6}\b/gi)||[])];
 // Geometry is untouched; presentation attributes generated by old scripts use the same palette.
 for(const color of svgColors){const next=recolor(color);if(next!==color)for(const prop of ['fill','stroke'])css+=`\nsvg [${prop}="${color}" i]{${prop}:${next}}`;}
 for(const el of d.querySelectorAll('[style]')){
  const style=el.getAttribute('style').replaceAll('\\','\\\\').replaceAll('"','\\"');
  for(const prop of ['color','background','background-color','border-color']){const value=el.style.getPropertyValue(prop),next=recolor(value);if(value&&next!==value)css+=`\n[style="${style}"]{${prop}:${next}!important}`;}
 }
 const base=':root{'+Object.entries(colors).map(([k,v])=>`--bhcs-${k}:${v}`).join(';')+'}';
 const shared=`
html,body{background-color:var(--bhcs-bg)}
button,input,select,.topic-logo,.logo,.total,.badge{border-radius:6px}
input[type="checkbox"],input[type="radio"]{accent-color:var(--bhcs-green)}
.top .logo,.top .topic-logo{color:#fff;background-color:var(--bhcs-green)}
.top h1 b{color:#fff}
header.no-print>div:first-child h1::before{color:#fff}
header.no-print>div:first-child>div:first-child>div:first-child{color:#fff!important}
:root body :is(#generate,#gen,#btn-regenerate,button[onclick="generateExam()"]){background:#E8620C!important;color:#fff!important;border-color:#E8620C!important;box-shadow:none!important}
:root body :is(#print,#btn-print-questions,#btn-print-answers,button[onclick^="printWorksheet("]){background:#fff!important;color:#16233A!important;border-color:#16233A!important;box-shadow:inset 0 0 0 1px #16233A!important}
button:focus-visible,input:focus-visible,select:focus-visible{outline-color:#C8352B}
`;
 // The sole all-media change requested by P1 is the red of teacher answers.
 const answer='.ans,.ans *,.answer,.note-answer,.sd,[id^="solution-"] ,[id^="solution-"] *,[id^="solution-box-"] ,[id^="solution-box-"] *{color:#C8352B!important}';
 const brand=`\n<style id="bhcs-math-brand">\n/* P1: screen palette only; original print rules and worksheet geometry are preserved. */\n@media screen{\n${base}\n${css}\n${shared}}\n${answer}\n</style>\n`;
 let next=original.replace(/(<meta\s+name="theme-color"\s+content=")[^"]+("\s*\/?>)/i,'$1#16233A$2');
 if(!/name="theme-color"/.test(next))next=next.replace('</head>','<meta name="theme-color" content="#16233A"></head>');
 next=next.replace('</head>',brand+'</head>');
 fs.writeFileSync(target,next);dom.window.close();
}
console.log(`Built P1 screen palette for ${files.length} single-file worksheets; ${cardCount} links`);
