const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {JSDOM,VirtualConsole}=require('jsdom');
const root=path.resolve(__dirname,'..');
function open(file){const errors=[],frames=[];const vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e.message));vc.on('error',e=>errors.push(String(e)));
 const dom=new JSDOM(fs.readFileSync(path.join(root,'tools',file),'utf8'),{url:'https://www.bhcs.com.tw/tools/'+file+'?noga=1',runScripts:'dangerously',virtualConsole:vc,beforeParse(w){w.HTMLCanvasElement.prototype.getContext=()=>new Proxy({measureText:s=>({width:s.length*8}),createLinearGradient:()=>({addColorStop(){}}),createRadialGradient:()=>({addColorStop(){}})},{get:(o,k)=>o[k]||(()=>{}),set:(o,k,v)=>(o[k]=v,true)});w.requestAnimationFrame=f=>(frames.push(f),frames.length);w.cancelAnimationFrame=()=>{};w.matchMedia=()=>({matches:true});w.confirm=()=>true;w.print=()=>{}}});
 const w=dom.window,d=w.document,$=id=>d.getElementById(id),event=(el,type)=>el.dispatchEvent(new w.Event(type,{bubbles:true})),select=(id,value)=>{$(id).value=value;event($(id),'change')};
 return {dom,w,d,$,errors,event,select,flush(){while(frames.length)frames.shift()(0)}};
}
(async()=>{
 const f=open('force-motion-lab.html');f.$('step').click();assert.match(f.$('timeValue').textContent,/—/,'Stepping requires a prediction');f.select('prediction','right');f.$('step').click();assert.equal(f.$('timeValue').textContent,'0.5 s');assert.equal(f.$('velocityValue').textContent,'1.5 m/s');assert.equal(f.$('accelValue').textContent,'3 m/s²');assert.equal(f.$('addRecord').disabled,false);f.$('step').click();assert.equal(f.$('timeValue').textContent,'1 s');assert.deepEqual(f.errors,[]);f.dom.window.close();console.log('PASS force first-step prediction, result reveal and subsequent stepping');
 const m=open('microscope-lab.html'),pad=m.$('slide-pad');pad.getBoundingClientRect=()=>({width:320});pad.setPointerCapture=()=>{};pad.releasePointerCapture=()=>{};
 const pointer=(type,x,y)=>{const e=new m.w.Event(type,{bubbles:true,cancelable:true});Object.assign(e,{pointerId:1,button:0,clientX:x,clientY:y});pad.dispatchEvent(e)};
 pointer('pointerdown',10,10);pointer('pointermove',80,40);m.flush();assert.equal(m.$('stageX').value,'0','No movement before prediction');
 m.select('prediction','narrower');m.$('begin').click();m.$('autofocus').click();pointer('pointerdown',10,10);pointer('pointermove',80,40);m.flush();assert.equal(m.$('stageX').value,'118');assert.equal(m.$('stageY').value,'-51');assert.match(m.$('movementValue').textContent,/片右→像左/);assert.match(m.$('microCoach').textContent,/第 4 步/);
 pointer('pointercancel',80,40);pointer('pointermove',1000,1000);m.flush();assert.equal(m.$('stageX').value,'118','Cancel ends drag');
 pointer('pointerdown',0,0);pointer('pointermove',10000,-10000);pointer('pointerup',10000,-10000);m.flush();assert.equal(m.$('stageX').value,'320');assert.equal(m.$('stageY').value,'320');
 pad.dispatchEvent(new m.w.KeyboardEvent('keydown',{key:'Home',bubbles:true}));m.flush();assert.equal(m.$('stageX').value,'0');assert.equal(m.$('stageY').value,'0');pad.dispatchEvent(new m.w.KeyboardEvent('keydown',{key:'ArrowLeft',bubbles:true}));m.flush();assert.equal(m.$('stageX').value,'-5');assert.equal(m.$('stageX').validity.stepMismatch,false,'Five-unit keyboard moves must be valid range values');assert.equal(m.$('stageY').step,'1');
 m.select('specimen','cheek');m.$('autofocus').click();assert.match(m.$('microCoach').textContent,/第 3 步/);assert.deepEqual(m.errors,[]);m.dom.window.close();console.log('PASS microscope drag, inverse directions, bounds, cancel, keyboard, reset and guidance');
 const g=open('genetics-simulation-lab.html');g.select('prediction','0.25');g.$('cross').click();let cells=[...g.d.querySelectorAll('.punnettChoice')];assert.equal(cells.length,4);assert.equal(cells.filter(b=>b.dataset.genotype==='tt').length,1);cells.find(b=>b.dataset.genotype==='tt').click();assert.match(g.$('punnett-detail').textContent,/提供 t.*提供 t.*tt（矮莖）/);assert.equal(g.d.querySelectorAll('[aria-pressed=true]').length,1);g.select('trait','color');g.select('prediction','0.25');g.$('cross').click();cells=[...g.d.querySelectorAll('.punnettChoice')];assert.ok(cells.every(b=>!b.textContent.includes('莖')));assert.deepEqual(g.errors,[]);g.dom.window.close();console.log('PASS interactive Punnett combinations, selection and trait changes');
 const moon=open('science/moon-eclipse.html');moon.select('prediction','none');moon.$('run').click();assert.equal(moon.d.querySelectorAll('.moon-panel').length,2);assert.equal(moon.$('moon-explore').disabled,false);moon.$('moon-explore').checked=true;moon.event(moon.$('moon-explore'),'change');moon.d.querySelector('[data-moon-phase="180"]').click();assert.match(moon.$('diagram').textContent,/望（滿月）/);assert.equal(moon.$('add-record').disabled,true);assert.equal(moon.$('prediction').value,'');moon.$('moon-explore').checked=false;moon.event(moon.$('moon-explore'),'change');assert.equal(moon.$('diagram').querySelector('svg'),null);moon.select('prediction','lunar');moon.$('run').click();assert.equal(moon.$('add-record').disabled,false);assert.deepEqual(moon.errors,[]);moon.dom.window.close();console.log('PASS moon phase presets, live exploration, stale-record prevention and prediction flow');
 const {moonLitPath}=await import('./science/diagrams.mjs');for(let phase=0;phase<=360;phase+=5){const pts=[...moonLitPath(phase).matchAll(/(-?[\d.]+),(-?[\d.]+)/g)].map(m=>[+m[1],+m[2]]);let twice=0;for(let i=0;i<pts.length;i++){const a=pts[i],b=pts[(i+1)%pts.length];twice+=a[0]*b[1]-b[0]*a[1]}const area=Math.abs(twice)/2/Math.PI/10000;assert.ok(Math.abs(area-(1-Math.cos(phase*Math.PI/180))/2)<.001,'Phase mask area must match illumination');}console.log('PASS 73 moon masks match the analytical illuminated fraction');
})().catch(e=>{console.error(e);process.exitCode=1});
